{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"UK_Cohorts\",\"UK BDMs\",\"ACR\",\"WECohort\",\"Canada FSI Cohorts\",\"WE_BDM\",\"Canada_FSI_BDM\",\"Canada E&R-BDM\",\"Sell BY Design\",\"Date\",\"Canada FSI-BDM-16May\",\"ACR_Export\",\"uk bdm 23may\",\"uk bdm 23may (2)\",\"uk bdm 23may (3)\",\"WE bdm\",\"WE bdm (2)\",\"Canada E&R BDM\",\"Canada E&R BDM (2)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.828.0 (23.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Canada FSI-BDM-16May",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\BDM Data\\BDM by Cohorts_Master.xlsx\"), null, true),",
          "    #\"Canada FSI_Sheet\" = Source{[Item=\"Canada FSI\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Canada FSI_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type text}, {\"As of April 5th\", type any}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"As of May 16\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column6\"}),",
          "    #\"Promoted Headers1\" = Table.PromoteHeaders(#\"Removed Columns\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"Column1\", type text}, {\"# Stakeholder Map\", Int64.Type}, {\"# of Contacts\", Int64.Type}, {\"Non IT BDMs\", Int64.Type}, {\"Date of Data Pull\", type date}, {\"# Stakeholder Map_1\", Int64.Type}, {\"# of Contacts_2\", Int64.Type}, {\"Non IT BDMs_3\", Int64.Type}, {\"Date of Data Pull_4\", type date}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"Column1\", \"Account Name\"}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns\",{\"# Stakeholder Map\", \"# of Contacts\", \"Non IT BDMs\", \"Date of Data Pull\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"# Stakeholder Map_1\", \"# Stakeholder Map\"}, {\"# of Contacts_2\", \"# of Contacts\"}, {\"Non IT BDMs_3\", \"Non IT BDMs\"}, {\"Date of Data Pull_4\", \"Date of Data Pull\"}})",
          "in",
          "    #\"Renamed Columns1\""
        ],
        "kind": "m",
        "lineageTag": "e541d974-2096-45b5-9469-d72fe58ddeee",
        "queryGroup": "AUX"
      },
      {
        "name": "ACR_Export",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\ACR L^0C Baseline 05.05.2023.xlsx\"), null, true),",
          "    Export_Sheet = Source{[Item=\"Export\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Customer\", type text}, {\"Column2\", type text}, {\"ACR $\", type any}, {\"ACR YoY%\", type any}, {\"ACR $_1\", type any}, {\"ACR YoY%_2\", type any}, {\"ACR $_3\", type any}, {\"ACR YoY%_4\", type any}, {\"ACR $_5\", type any}, {\"ACR YoY%_6\", type any}, {\"ACR $_7\", type any}, {\"ACR YoY%_8\", type any}, {\"ACR $_9\", type any}, {\"ACR YoY%_10\", type any}, {\"ACR $_11\", type any}, {\"ACR YoY%_12\", type any}, {\"ACR $_13\", type any}, {\"ACR YoY%_14\", type any}, {\"ACR $_15\", type any}, {\"ACR YoY%_16\", type any}, {\"ACR $_17\", type any}, {\"ACR YoY%_18\", type any}, {\"ACR $_19\", type any}, {\"ACR YoY%_20\", type any}, {\"ACR $_21\", type any}, {\"ACR YoY%_22\", type any}, {\"ACR $_23\", type any}, {\"ACR YoY%_24\", type any}, {\"ACR $_25\", type any}, {\"ACR YoY%_26\", type any}, {\"ACR $_27\", type any}, {\"ACR YoY%_28\", type any}, {\"ACR $_29\", type any}, {\"ACR YoY%_30\", type any}, {\"ACR $_31\", type any}, {\"ACR YoY%_32\", type any}, {\"ACR $_33\", type any}, {\"ACR YoY%_34\", type any}, {\"ACR $_35\", type any}, {\"ACR YoY%_36\", type any}, {\"ACR $_37\", type any}, {\"ACR YoY%_38\", type any}, {\"ACR $_39\", type any}, {\"ACR YoY%_40\", type any}, {\"ACR $_41\", type any}, {\"ACR YoY%_42\", type any}, {\"ACR $_43\", type any}, {\"ACR YoY%_44\", type any}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "57c21a40-83c8-46c7-947b-b511b26445b2"
      },
      {
        "name": "uk bdm 23may",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\BDM Data\\BDM by Cohorts_Master (1).xlsx\"), null, true),",
          "    #\"UK BDMs_Sheet\" = Source{[Item=\"UK BDMs\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"UK BDMs_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type any}, {\"Column2\", type text}, {\"As of March 28th\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"As of May 17\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type text}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}}),",
          "    #\"Promoted Headers1\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"TPID\", Int64.Type}, {\"Column1\", type text}, {\"# Stakeholder Map\", Int64.Type}, {\"# of Contacts\", Int64.Type}, {\"Non IT BDMs\", Int64.Type}, {\"Date of Data Pull\", type date}, {\"# of Contacts2\", Int64.Type}, {\"Non IT BDMs2\", Int64.Type}, {\"Date of Data Pull2\", type date}, {\"Column2\", type text}, {\"# of Contacts3\", Int64.Type}, {\"Non IT BDMs3\", Int64.Type}, {\"Date of Data Pull3\", type date}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{ \"# of Contacts2\", \"Non IT BDMs2\", \"Date of Data Pull2\", \"Column2\", \"# of Contacts3\", \"Non IT BDMs3\", \"Date of Data Pull3\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each ([Column1] <> null)),",
          "    #\"Appended Query\" = Table.Combine({#\"Filtered Rows\", #\"uk bdm 23may (2)\"}),",
          "    #\"Appended Query1\" = Table.Combine({#\"Appended Query\", #\"uk bdm 23may (3)\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Appended Query1\",{{\"Column1\", \"Account Name\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "0c6b0a92-d234-4914-ac7a-6bc3a9ad8dda",
        "queryGroup": "23 May bdm"
      },
      {
        "name": "uk bdm 23may (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\BDM Data\\BDM by Cohorts_Master (1).xlsx\"), null, true),",
          "    #\"UK BDMs_Sheet\" = Source{[Item=\"UK BDMs\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"UK BDMs_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type any}, {\"Column2\", type text}, {\"As of March 28th\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"As of May 17\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type text}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}}),",
          "    #\"Promoted Headers1\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"TPID\", Int64.Type}, {\"Column1\", type text}, {\"# Stakeholder Map\", Int64.Type}, {\"# of Contacts\", Int64.Type}, {\"Non IT BDMs\", Int64.Type}, {\"Date of Data Pull\", type date}, {\"# of Contacts2\", Int64.Type}, {\"Non IT BDMs2\", Int64.Type}, {\"Date of Data Pull2\", type date}, {\"Column2\", type text}, {\"# of Contacts3\", Int64.Type}, {\"Non IT BDMs3\", Int64.Type}, {\"Date of Data Pull3\", type date}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"# of Contacts\", \"Non IT BDMs\", \"Date of Data Pull\", \"Column2\", \"# of Contacts3\", \"Non IT BDMs3\", \"Date of Data Pull3\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each ([Column1] <> null)),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Filtered Rows\",{{\"# of Contacts2\", \"# of Contacts\"}, {\"Non IT BDMs2\", \"Non IT BDMs\"}, {\"Date of Data Pull2\", \"Date of Data Pull\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "f99ddb33-5f8b-45cb-87f1-c9d699120b1b",
        "queryGroup": "23 May bdm"
      },
      {
        "name": "uk bdm 23may (3)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\BDM Data\\BDM by Cohorts_Master (1).xlsx\"), null, true),",
          "    #\"UK BDMs_Sheet\" = Source{[Item=\"UK BDMs\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"UK BDMs_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type any}, {\"Column2\", type text}, {\"As of March 28th\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"As of May 17\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type text}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}}),",
          "    #\"Promoted Headers1\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"TPID\", Int64.Type}, {\"Column1\", type text}, {\"# Stakeholder Map\", Int64.Type}, {\"# of Contacts\", Int64.Type}, {\"Non IT BDMs\", Int64.Type}, {\"Date of Data Pull\", type date}, {\"# of Contacts2\", Int64.Type}, {\"Non IT BDMs2\", Int64.Type}, {\"Date of Data Pull2\", type date}, {\"Column2\", type text}, {\"# of Contacts3\", Int64.Type}, {\"Non IT BDMs3\", Int64.Type}, {\"Date of Data Pull3\", type date}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{ \"# of Contacts\", \"Non IT BDMs\", \"Date of Data Pull\", \"# of Contacts2\", \"Non IT BDMs2\", \"Date of Data Pull2\", \"Column2\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each ([Column1] <> null)),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Filtered Rows\",{{\"Non IT BDMs3\", \"Non IT BDMs\"}, {\"Date of Data Pull3\", \"Date of Data Pull\"}, {\"# of Contacts3\", \"# of Contacts\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "80cbcb29-0cf1-4e7e-8332-47d4556b2b9d",
        "queryGroup": "23 May bdm"
      },
      {
        "name": "WE bdm",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\BDM Data\\BDM by Cohorts_Master (1).xlsx\"), null, true),",
          "    WE_Sheet = Source{[Item=\"WE\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(WE_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Account Name\", type text}, {\"# Stakeholder Map\", Int64.Type}, {\"# of Contacts\", Int64.Type}, {\"Non IT BDM\", Int64.Type}, {\"Date of Data Pull\", type date}, {\"Column6\", type any}, {\"# of Contacts_1\", Int64.Type}, {\"Non IT BDM_2\", Int64.Type}, {\"Date of Data Pull_3\", type date}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column6\", \"# of Contacts_1\", \"Non IT BDM_2\", \"Date of Data Pull_3\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each ([Account Name] <> null)),",
          "    #\"Appended Query\" = Table.Combine({#\"Filtered Rows\", #\"WE bdm (2)\"})",
          "in",
          "    #\"Appended Query\""
        ],
        "kind": "m",
        "lineageTag": "334464ed-041a-4f15-ab8d-d0edc10921de",
        "queryGroup": "23 May bdm"
      },
      {
        "name": "WE bdm (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\BDM Data\\BDM by Cohorts_Master (1).xlsx\"), null, true),",
          "    WE_Sheet = Source{[Item=\"WE\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(WE_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Account Name\", type text}, {\"# Stakeholder Map\", Int64.Type}, {\"# of Contacts\", Int64.Type}, {\"Non IT BDM\", Int64.Type}, {\"Date of Data Pull\", type date}, {\"Column6\", type any}, {\"# of Contacts_1\", Int64.Type}, {\"Non IT BDM_2\", Int64.Type}, {\"Date of Data Pull_3\", type date}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"# of Contacts\", \"Non IT BDM\", \"Date of Data Pull\", \"Column6\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each ([Account Name] <> null)),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Filtered Rows\",{{\"# of Contacts_1\", \"# of Contacts\"}, {\"Non IT BDM_2\", \"Non IT BDM\"}, {\"Date of Data Pull_3\", \"Date of Data Pull\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "8dda06e2-b82b-45f0-941a-9c2f28865834",
        "queryGroup": "23 May bdm"
      },
      {
        "name": "Canada E&R BDM",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\BDM Data\\BDM by Cohorts_Master (1).xlsx\"), null, true),",
          "    #\"Canada E&R_Sheet\" = Source{[Item=\"Canada E&R\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Canada E&R_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type text}, {\"As of April 5th\", type any}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"As of May 22nd\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}}),",
          "    #\"Promoted Headers1\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"Column1\", type text}, {\"# Stakeholder Map\", Int64.Type}, {\"# of Contacts\", Int64.Type}, {\"Non IT BDMs\", Int64.Type}, {\"Date of Data Pull\", type date}, {\"Column6\", type any}, {\"# Stakeholder Map_1\", Int64.Type}, {\"# of Contacts_2\", Int64.Type}, {\"Non IT BDMs_3\", Int64.Type}, {\"Date of Data Pull_4\", type date}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"Column6\", \"# Stakeholder Map_1\", \"# of Contacts_2\", \"Non IT BDMs_3\", \"Date of Data Pull_4\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each ([Column1] <> null)),",
          "    #\"Appended Query\" = Table.Combine({#\"Filtered Rows\", #\"Canada E&R BDM (2)\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Appended Query\",{{\"Column1\", \"Account\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "98b2c06a-493e-4c98-8468-dd49285e5d58",
        "queryGroup": "23 May bdm"
      },
      {
        "name": "Canada E&R BDM (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\BDM Data\\BDM by Cohorts_Master (1).xlsx\"), null, true),",
          "    #\"Canada E&R_Sheet\" = Source{[Item=\"Canada E&R\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Canada E&R_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type text}, {\"As of April 5th\", type any}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"As of May 22nd\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}}),",
          "    #\"Promoted Headers1\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"Column1\", type text}, {\"# Stakeholder Map\", Int64.Type}, {\"# of Contacts\", Int64.Type}, {\"Non IT BDMs\", Int64.Type}, {\"Date of Data Pull\", type date}, {\"Column6\", type any}, {\"# Stakeholder Map_1\", Int64.Type}, {\"# of Contacts_2\", Int64.Type}, {\"Non IT BDMs_3\", Int64.Type}, {\"Date of Data Pull_4\", type date}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"# Stakeholder Map\", \"# of Contacts\", \"Non IT BDMs\", \"Date of Data Pull\", \"Column6\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"# Stakeholder Map_1\", \"# Stakeholder Map\"}, {\"# of Contacts_2\", \"# of Contacts\"}, {\"Non IT BDMs_3\", \"Non IT BDMs\"}, {\"Date of Data Pull_4\", \"Date of Data Pull\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each ([Column1] <> null))",
          "in",
          "    #\"Filtered Rows\""
        ],
        "kind": "m",
        "lineageTag": "2c0d72df-3c38-4ee3-9a99-edc92c0f0d1e",
        "queryGroup": "23 May bdm"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Fact-Table"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Dimension"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "AUX"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "23 May bdm"
      }
    ],
    "relationships": [
      {
        "name": "b24e4931-4449-4755-ba8c-b1db683ee1f2",
        "fromColumn": "Est. Start Date",
        "fromTable": "WECohort",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2ba381bf-04fa-46af-a844-f8c961d9e64e"
      },
      {
        "name": "9f21b99b-9cfd-47ab-81e9-c88da99a1e44",
        "fromColumn": "Est. Completion Date",
        "fromTable": "WECohort",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a2335a29-0813-43ca-8d8a-b50eae7ca3d2"
      },
      {
        "name": "57dd107a-5c90-4ef9-a506-f16d0dff3a72",
        "fromColumn": "Date",
        "fromTable": "Sell BY Design",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2229f48f-9f2a-4de4-bc1a-b9a27b7c9796"
      },
      {
        "name": "d9858430-43a0-4a8c-9e33-d3d9b179b296",
        "fromColumn": "Translated Account",
        "fromTable": "UK_Cohorts",
        "toColumn": "Account Name",
        "toTable": "Sell BY Design"
      },
      {
        "name": "0aa363b4-dc77-4290-add1-bbe77ac178ad",
        "fromColumn": "Translated Account",
        "fromTable": "Canada FSI Cohorts",
        "toColumn": "Account Name",
        "toTable": "Sell BY Design"
      },
      {
        "name": "9ee37c75-d11a-470c-939b-67601753f5a6",
        "fromColumn": "Translated Account",
        "fromTable": "WECohort",
        "toColumn": "Account Name",
        "toTable": "Sell BY Design"
      },
      {
        "name": "d2779c01-8738-4d83-86b7-fe70fe0b3792",
        "fromColumn": "Account",
        "fromTable": "WE_BDM",
        "toColumn": "Account Name",
        "toTable": "Sell BY Design"
      },
      {
        "name": "bc7e612c-2a01-43fe-b5e9-fb9b492ab3b0",
        "fromColumn": "Date",
        "fromTable": "Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3822d13c-7d86-403a-bcf6-6646d6f66cbe"
      },
      {
        "name": "ec777d75-75b5-4a8c-93e3-3556b98f5eb9",
        "fromColumn": "Date of Data Pull",
        "fromTable": "UK BDMs",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "84de0435-2599-4cbc-905c-7dfddbed5357",
        "fromColumn": "Date",
        "fromTable": "Canada E&R-BDM",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "db614cce-fe24-4f2e-a44c-ac3825f42d08",
        "fromColumn": "Date",
        "fromTable": "WE_BDM",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "3701921f-2415-4522-8962-84457956a75c",
        "fromColumn": "Date",
        "fromTable": "Canada FSI Cohorts",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "0b20be3b-3d3c-4302-acbb-6fa84a7d2a6f",
        "fromColumn": "Date",
        "fromTable": "UK_Cohorts",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "5a07383c-573f-46f7-93f7-a15db603ab79",
        "fromColumn": "Date",
        "fromTable": "WECohort",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "bc802a86-5521-4f56-81d1-001d4696436a",
        "fromColumn": "Account Name",
        "fromTable": "Canada_FSI_BDM",
        "toColumn": "Account Name",
        "toTable": "Sell BY Design"
      },
      {
        "name": "20be388e-2516-49cd-ba6b-9a0bb67e7f22",
        "fromColumn": "Date",
        "fromTable": "Canada_FSI_BDM",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "0480b92b-7181-4f6c-8238-6065dada1b1e",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Account",
        "fromTable": "ACR",
        "toCardinality": "many",
        "toColumn": "Translated Account",
        "toTable": "Canada FSI Cohorts"
      },
      {
        "name": "f4954633-fc3d-46ae-b5fc-4587fae0aed1",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Account",
        "fromTable": "ACR",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "Translated Account",
        "toTable": "WECohort"
      },
      {
        "name": "bfc0db4b-a777-41ac-989a-5e10974c1af7",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Account",
        "fromTable": "ACR",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "Translated Account",
        "toTable": "UK_Cohorts"
      },
      {
        "name": "9b37526f-f937-4d9f-b16b-5fce41c51833",
        "fromColumn": "Account Name",
        "fromTable": "UK BDMs",
        "toColumn": "Account Name",
        "toTable": "Sell BY Design"
      },
      {
        "name": "86095f01-81b4-4939-879a-8673a22a77be",
        "fromColumn": "Account",
        "fromTable": "Canada E&R-BDM",
        "toColumn": "Account Name",
        "toTable": "Sell BY Design"
      },
      {
        "name": "7e0e6440-e8e0-4e44-b9ef-46f21c0946e5",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Created month",
        "fromTable": "Date",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "Created Month",
        "toTable": "UK_Cohorts"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "ACR",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71df0bd3-78f2-4141-b2f1-276881afaee8",
            "sourceColumn": "Account",
            "summarizeBy": "none"
          },
          {
            "name": "Baseline&Current",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(ACR[Month No]<=\"3\",\"Baseline\",\"Current Month\")",
            "isDataTypeInferred": true,
            "lineageTag": "cd8c9cc7-9517-441b-af55-cfad537ce2fe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"ACR\",\"TableItemName\":\"Month (groups)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "9922d0ac-e705-4bd2-a2e1-50aac86932d1",
            "sortByColumn": "Month No",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Month (groups)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"a\",\"Entity\":\"ACR\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"a\"}},\"Property\":\"Month\"}}],\"GroupItems\":[{\"DisplayName\":\"(Blank)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"February & January & March\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"a\"}},\"Property\":\"Month\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'January'\"}}],[{\"Literal\":{\"Value\":\"'February'\"}}],[{\"Literal\":{\"Value\":\"'March'\"}}]]}}},{\"DisplayName\":\"Other\"}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('ACR'[Month]),",
              "\t\"(Blank)\",",
              "\t'ACR'[Month] IN {\"January\",",
              "\t\t\"February\",",
              "\t\t\"March\"},",
              "\t\"February & January & March\",",
              "\t\"Other\"",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "ACR"
                          }
                        },
                        "Property": "Month"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2b73b5c3-e534-4b17-ad05-0d0b219a2b3f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7318aa9-b2f1-4fa7-be47-76afec5b73ca",
            "sourceColumn": "Month No",
            "summarizeBy": "none"
          },
          {
            "name": "Running Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "VAR PdtRank =",
              "    RANKX(",
              "        ALL(ACR[Month]),",
              "        CALCULATE(SUM(ACR[Value])),,",
              "        DESC,",
              "        Dense",
              "    )",
              "VAR RunningTotal =",
              "    CALCULATE(SUM(ACR[Value])",
              "        ,",
              "        FILTER(",
              "            ALL(ACR[Month]),",
              "            PdtRank >= RANKX(",
              "                        ALL(ACR[Month]),",
              "                        CALCULATE(SUM(ACR[Value])),,",
              "                        DESC,",
              "                        Dense",
              "                    )",
              "        )",
              "    )",
              "RETURN",
              "   RunningTotal"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3300c215-c830-481c-901e-0afd21c38805",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "97b72655-5d27-4abf-a19d-279d0e964a2b",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "cda34061-bd75-4eb3-b499-5dea720d3a69",
        "measures": [
          {
            "name": "Value running total in Month",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "\tSUM('ACR'[Value]),",
              "\tFILTER(",
              "\t\tALLSELECTED('ACR'[Month]),",
              "\t\tISONORAFTER('ACR'[Month], MAX('ACR'[Month]), DESC)",
              "\t)",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "RunningTotal",
                  "version": 0
                }
              }
            ],
            "lineageTag": "64316cd8-d082-4741-8ec4-97df3946a643"
          },
          {
            "name": "Value running total in Month No",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "\tSUM('ACR'[Value]),",
              "\tFILTER(",
              "\t\tALLSELECTED('ACR'[Month No]),",
              "\t\tACR[Month No]<=MAX(ACR[Month No])",
              "\t)",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "RunningTotal",
                  "version": 0
                }
              }
            ],
            "lineageTag": "af3a2d0c-d009-413e-84c6-e498c4ce7c7e"
          },
          {
            "name": "New Running Acr",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "\tSUM('ACR'[Value]),",
              "\t",
              "\t\tFILTER(ALL('ACR'),",
              "\t\tACR[Month No]<=MAX(ACR[Month No])",
              "\t)",
              ")"
            ],
            "lineageTag": "062a0cb9-89cc-4ff9-b971-e9332fec88d0"
          },
          {
            "name": "Running Value Summary Acr",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR PdtRank =",
              "    RANKX(",
              "        ALL(ACR[Month]),",
              "        CALCULATE(SUM(ACR[Value])),,",
              "        DESC,",
              "        Dense",
              "    )",
              "VAR RunningTotal =",
              "    CALCULATE(SUM(ACR[Value])",
              "        ,",
              "        FILTER(",
              "            ALL(ACR[Month]),",
              "            PdtRank >= RANKX(",
              "                        ALL(ACR[Month]),",
              "                        CALCULATE(SUM(ACR[Value])),,",
              "                        DESC,",
              "                        Dense",
              "                    )",
              "        )",
              "    )",
              "RETURN",
              "IF(CALCULATE(SUM(ACR[Value]))<>BLANK(),",
              "   RunningTotal)"
            ],
            "lineageTag": "be2c48fb-26f1-440d-ac18-bac88605326c"
          },
          {
            "name": "UK ACR Test",
            "expression": "CALCULATE(MIN(ACR[Month]),USERELATIONSHIP(ACR[Account],'UK_Cohorts'[Translated Account]))",
            "lineageTag": "e9fe39cd-cea7-42fc-8042-f028cce3cc2c"
          },
          {
            "name": "WE Cohort ACR Value",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM(ACR[Value]),USERELATIONSHIP(ACR[Account],'WECohort'[Translated Account]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "cfc89d46-df1f-4280-8e8c-f9d75c240585"
          }
        ],
        "partitions": [
          {
            "name": "ACR-d15d6af8-49f1-44c7-a0ab-96c1cb06ee6d",
            "mode": "import",
            "queryGroup": "Fact-Table",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\ACR Data\\ACR L&C Baseline 05.05.2023.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"L&C Program\", type text}, {\"Yes\", type any}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([#\"L&C Program\"] <> null)),",
                "    #\"Promoted Headers1\" = Table.PromoteHeaders(#\"Filtered Rows\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"Row Labels\", type text}, {\"Sum of January 2023\", type number}, {\"Sum of February 2023\", type number}, {\"Sum of March 2023\", type number}, {\"Sum of April 2023\", type number}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"Row Labels\", \"Account\"}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Renamed Columns\", each ([Account] <> \"Grand Total\")),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Filtered Rows1\",{{\"Sum of January 2023\", \"January\"}, {\"Sum of February 2023\", \"February\"}, {\"Sum of March 2023\", \"March\"}, {\"Sum of April 2023\", \"April\"}}),",
                "    #\"Unpivoted Columns\" = Table.UnpivotOtherColumns(#\"Renamed Columns1\", {\"Account\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Unpivoted Columns\",{{\"Attribute\", \"Month\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns2\", \"Month No\", each if [Month] = \"January\" then 1",
                "              else if [Month] = \"February\" then 2",
                "              else if [Month] = \"March\" then 3",
                "              ",
                "              else  4),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Added Custom\",\"Belfius Bank NV\",\"Belfius\",Replacer.ReplaceText,{\"Account\"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Canada E&R-BDM",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "# Stakeholder Map",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ebc08e75-f4e4-4815-9626-0de047441db1",
            "sourceColumn": "# Stakeholder Map",
            "summarizeBy": "sum"
          },
          {
            "name": "# of Contacts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8567afa7-178c-462c-af1e-95898756b39b",
            "sourceColumn": "# of Contacts",
            "summarizeBy": "sum"
          },
          {
            "name": "Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d381801-9802-4e8e-b235-df813ba6eda4",
            "sourceColumn": "Account",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "735904fb-0b7a-4566-b230-15b09a638bd7",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Date_New",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Canada E&R-BDM'[Date],\"mmmm-dd-yyyy\")",
            "isDataTypeInferred": true,
            "lineageTag": "52a4ba7b-2c0a-44ad-a49b-43e7c718d7bd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "IT BDMs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c32e0206-1c76-4416-b5c8-8a7f86d0febe",
            "sourceColumn": "IT BDMs",
            "summarizeBy": "sum"
          },
          {
            "name": "Non IT BDMs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b494983f-bf51-47cf-8a5f-8d58a67e98e0",
            "sourceColumn": "Non IT BDMs",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "5dc01a15-5b51-4a21-85f1-d884500df90d",
        "measures": [
          {
            "name": "Welcome Text",
            "expression": [
              "",
              "",
              "VAR Hour = HOUR(NOW())",
              "",
              "VAR Greeting =",
              "",
              "SWITCH(",
              "",
              "    TRUE(),",
              "",
              "    Hour >= 0 && Hour < 5, \"Good Night\",",
              "",
              "    Hour >= 5 && Hour < 12, \"Good Morning\",",
              "",
              "    Hour >= 12 && Hour < 18, \"Good Afternoon\",",
              "",
              "    Hour >= 18 && Hour < 24, \"Good Evening\"",
              "",
              ")",
              "",
              "RETURN",
              "",
              "Greeting"
            ],
            "lineageTag": "2b3d91ff-7869-4d87-8dcc-0b62942e3599"
          },
          {
            "name": "max_Qualified_pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(MAX('UK_Cohorts'[Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6ec1fa3b-ed79-4deb-a03a-a9da7d60fe87"
          },
          {
            "name": "Min_qualified_pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(MIN('UK_Cohorts'[Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "2007daca-af49-4136-97bf-c5f133d6367e"
          },
          {
            "name": "Count_Account",
            "expression": "CALCULATE(DISTINCTCOUNT('UK_Cohorts'[Translated Account]))",
            "formatString": "0",
            "lineageTag": "cf7d6342-12fb-46ff-b6ef-11d946a1d731"
          },
          {
            "name": "Total opportunity count",
            "expression": "CALCULATE(DISTINCTCOUNT('UK_Cohorts'[Opportunity Name]))",
            "formatString": "0",
            "lineageTag": "bde00045-38c8-4699-b1be-48d0aefb8f72"
          },
          {
            "name": "Remaining",
            "expression": "[Total opportunity count]-[Count of start till today]",
            "formatString": "0",
            "lineageTag": "e8ae9961-249c-4100-a686-0ff37e378b95"
          },
          {
            "name": "Total Opportunity Completed",
            "expression": "IF(CALCULATE(DISTINCTCOUNTNOBLANK('UK Cohorts 18 April'[Opportunity Name]),'UK Cohorts 18 April'[Est. Completion Date]<=TODAY(),'UK Cohorts 18 April'[Est. Completion Date]<>BLANK())=BLANK(),0,CALCULATE(DISTINCTCOUNTNOBLANK('UK Cohorts 18 April'[Opportunity Name]),'UK Cohorts 18 April'[Est. Completion Date]<=TODAY(),'UK Cohorts 18 April'[Est. Completion Date]<>BLANK()))",
            "formatString": "0",
            "lineageTag": "672d88d2-3a0a-4d02-b002-181628ef35be"
          },
          {
            "name": "Canada_Qualified pipelin",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM('Canada FSI Cohorts'[Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "8561467d-008a-4374-b52a-ec3a7d54a9d6"
          },
          {
            "name": "WE_Account",
            "expression": "CALCULATE(FIRSTNONBLANK(WE[Column1.1],1),CROSSFILTER(WE[Column1.1],WECohort[Translated Account],Both))",
            "lineageTag": "e9b53db5-b0dd-4770-93a9-d7d1cb1748d9"
          },
          {
            "name": "Canada_max Qualified Pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(MAX('Canada FSI Cohorts'[Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d3f5fb6c-ec50-4c39-bc5d-daa46eb92773"
          },
          {
            "name": "Canada_min Qualified Pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(MIN('Canada FSI Cohorts'[Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "02c60b02-b848-440f-ace6-46748ab8b941"
          },
          {
            "name": "Canada_Average Qualified pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(AVERAGE('Canada FSI Cohorts'[Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "9cb38e2a-4995-4ae5-af43-c195d0e68b6d"
          },
          {
            "name": "Canada_Count_Translated account",
            "expression": "CALCULATE(DISTINCTCOUNT('Canada FSI Cohorts'[Translated Account]))",
            "formatString": "0",
            "lineageTag": "5cd82dfe-acdc-45ab-abd7-86bad7d6119e"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "400fc570-0767-499b-a6b7-ed330f399d18"
          },
          {
            "name": "Max We_Qualified pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(MAX('WECohort'[Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "9bc12934-b1f2-438b-bcd2-a8f124fc7b07"
          },
          {
            "name": "Min_We Qualified Pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(MIN('WECohort'[Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "94807eb5-66a2-487f-94bf-43863efac435"
          },
          {
            "name": "WE_Average Qualified Pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(AVERAGE('WECohort'[Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "eceb13d9-a13a-4674-ad17-89f3080eafd3"
          },
          {
            "name": "We_Count",
            "expression": "CALCULATE(DISTINCTCOUNT('WECohort'[Translated Account]))",
            "formatString": "0",
            "lineageTag": "a93e8757-f175-4797-bf45-c6f3ee944f64"
          },
          {
            "name": "Non  Qualified Pivot_Canada",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM('Pivot_Canada 17 April'[Sum of Non-Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "92db930c-e164-40c9-97bf-e81b567d60fb"
          },
          {
            "name": "Qualified_Pivot Canada",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM('Pivot_Canada 17 April'[Sum of Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "335efdb0-0d30-478f-adcb-3aacc9878ee8"
          },
          {
            "name": "Non it Canada Er",
            "expression": "CALCULATE(SUM('Canada E&R-BDM'[Non IT BDMs]))",
            "formatString": "0",
            "lineageTag": "57cb305f-14d5-414c-8639-b1d5bd0ddbef"
          },
          {
            "name": "IT BDms canada E&R",
            "expression": "CALCULATE(SUM('Canada E&R-BDM'[IT BDMs]))",
            "formatString": "0",
            "lineageTag": "81cbeb1e-3842-487d-875a-a1aa5282f629"
          },
          {
            "name": "Measure 2",
            "annotations": [
              {
                "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
                "value": "{\"formula\":\"Difference Of Stage1\",\"Expression\":null}"
              },
              {
                "name": "277cc1b9-af89-4597-8e15-cacc25c0886b",
                "value": "To use special characters in a measure name, enclose the entire name in brackets ( [] ) and add a ] to any closing brackets in the name."
              }
            ],
            "lineageTag": "d78b7092-1da2-4bc1-a729-edd3b759a6ea"
          },
          {
            "name": "Difference in stage 2 uk",
            "expression": "[UK Stage 2 For Baseline]",
            "formatString": "0",
            "lineageTag": "ae5d1ed5-ea03-44eb-aad1-713e9977ec2f"
          },
          {
            "name": "Color Code Summary",
            "expression": "SWITCH(SELECTEDVALUE('Date'[Date]),DATE(2023,04,10),\"#FF8420\",DATE(2023,04,18),\"#FF8420\",DATE(2023,05,08),\"#E75542\")",
            "lineageTag": "040d5542-5179-4718-834f-cd16c76aa036"
          }
        ],
        "partitions": [
          {
            "name": "Canada E&R-BDM-4d025125-22a7-46bb-ba19-f7526a2f5e5e",
            "mode": "import",
            "queryGroup": "Fact-Table",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Canada E&R BDM\",",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{ {\"Date of Data Pull\", \"Date\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Date\", type date}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type2\", \"IT BDMs\", each [#\"# of Contacts\"]-[Non IT BDMs]),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each ([Account] <> null)),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"IT BDMs\", Int64.Type}})",
                "in",
                "    #\"Changed Type3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Canada FSI Cohorts",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Committed Pipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8850be15-5722-4b2d-819c-802230a9592c",
            "sourceColumn": "Committed Pipeline",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd mmmm yyyy",
            "lineageTag": "b20852d6-125b-4c2b-86b6-d3ecf822374a",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DATEDIFF('Canada FSI Cohorts'[Est. Start Date],'Canada FSI Cohorts'[Est. Completion Date],DAY)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "629ae8b3-75d5-4e26-b5f1-eed5d229a548",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Est. Completion Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "string",
            "lineageTag": "c378df3d-f1aa-4bea-914f-87e2ee21d4af",
            "sourceColumn": "Est. Completion Date",
            "summarizeBy": "none"
          },
          {
            "name": "Est. Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee7d2580-9ef6-42be-ba09-17f34634530a",
            "sourceColumn": "Est. Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Industry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "225fe8da-6532-48ca-a290-c1207504a874",
            "sourceColumn": "Industry",
            "summarizeBy": "none"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Canada FSI Cohorts'[Date],\"mmmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "3af4d232-1320-4a44-b3bb-89941461be7f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Non-Qualified Pipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41347d1e-06b0-4283-88fb-538b709b85ee",
            "sourceColumn": "Non-Qualified Pipeline",
            "summarizeBy": "sum"
          },
          {
            "name": "Opportunity Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a075fd10-5e37-4fd2-ab26-a4c2e340f113",
            "sourceColumn": "Opportunity Name",
            "summarizeBy": "none"
          },
          {
            "name": "Qualified Pipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d18b67c8-adc5-45dd-929a-4f04ffdb49b4",
            "sourceColumn": "Qualified Pipeline",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales Stage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9214f5b0-b932-4f2f-bd88-bd26b0b3e42f",
            "sourceColumn": "Sales Stage",
            "summarizeBy": "none"
          },
          {
            "name": "SubRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc944c51-64b5-4f68-8759-e1c64b525362",
            "sourceColumn": "SubRegion",
            "summarizeBy": "none"
          },
          {
            "name": "Subsidiary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccc5ee9e-5103-4e5e-b2cb-a0fdf830e29c",
            "sourceColumn": "Subsidiary",
            "summarizeBy": "none"
          },
          {
            "name": "TPID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "string",
            "lineageTag": "126fcf7f-8b09-4bba-b2a1-55123e8a600d",
            "sourceColumn": "TPID",
            "summarizeBy": "none"
          },
          {
            "name": "Translated Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b041c109-5b1d-4e6a-b1d7-5c9356f36202",
            "sourceColumn": "Translated Account",
            "summarizeBy": "none"
          },
          {
            "name": "Uncommitted Pipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bab79cdc-7ad3-4e25-8a20-53a25053693a",
            "sourceColumn": "Uncommitted Pipeline",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c8ed38a1-11d9-4260-855a-fff4306807f3",
        "measures": [
          {
            "name": "Non Qualified (Running Canada FSI)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(",
              "                                      [Canada_Non Qualified Pipeline],",
              "                                      FILTER( ALL('Canada FSI Cohorts'[DATE]),'Canada FSI Cohorts'[DATE]<=MAX('Canada FSI Cohorts'[DATE]))) ",
              "",
              "                                      "
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d1215e27-e0c5-4086-b363-1e6d8a81c94d"
          },
          {
            "name": "Qualified (Running Canada FSI)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(",
              "                                      [Canada_Qualified Pipeline],",
              "                                      FILTER( ALL('Canada FSI Cohorts'[DATE]),'Canada FSI Cohorts'[DATE]<=MAX('Canada FSI Cohorts'[DATE])))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "83df9654-aa90-496d-baab-19759ed9903e"
          },
          {
            "name": "Canada_Non Qualified Pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM('Canada FSI Cohorts'[Non-Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "273e5827-933d-4023-b766-8dcdb86f3012"
          },
          {
            "name": "Canada_Non Qualified Pipeline-Avg",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('Canada FSI Cohorts'[Non-Qualified Pipeline]))",
            "lineageTag": "8acd4dc5-6b2e-42eb-aeba-dab6bbdea95c"
          },
          {
            "name": "Non Qualified (Running Canada FSI)-avg",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "Var Last = CALCULATE(",
              "                                      [Canada_Non Qualified Pipeline-Avg],",
              "                                      FILTER( ALL('Canada FSI Cohorts'[DATE]),'Canada FSI Cohorts'[DATE]<=MAX('Canada FSI Cohorts'[DATE])))",
              "Var FS = CALCULATE(",
              "                                      [Canada_Non Qualified Pipeline-Avg],",
              "                                      FILTER( ALL('Canada FSI Cohorts'[DATE]),'Canada FSI Cohorts'[DATE]<=MAX('Canada FSI Cohorts'[DATE])-1))",
              "Return ",
              "DIVIDE((Last-FS),FS)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2eb8df1f-5402-4d47-94c9-a9fe8692cee5"
          },
          {
            "name": "Qualified (Running Canada FSI)-avg",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "Var Last = CALCULATE(",
              "                                      [Canada_Qualified Pipeline],",
              "                                      FILTER( ALL('Canada FSI Cohorts'[DATE]),'Canada FSI Cohorts'[DATE]<=MAX('Canada FSI Cohorts'[DATE])))",
              "Var FS = CALCULATE(",
              "                                      [Canada_Qualified Pipeline],",
              "                                      FILTER( ALL('Canada FSI Cohorts'[DATE]),'Canada FSI Cohorts'[DATE]<=MAX('Canada FSI Cohorts'[DATE])-1))",
              "Return ",
              "DIVIDE((Last-FS),FS)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7d94a0df-fd36-4eda-851b-c95fcbc7d1b2"
          },
          {
            "name": "Canada FSI Color",
            "expression": "SWITCH(SELECTEDVALUE('Canada FSI Cohorts'[DATE]),DATE(2023,04,10),\"#FF8420\",DATE(2023,05,08),\"#E75542\")",
            "lineageTag": "e8fdd1b5-7ed8-4917-9514-bed9b58cf955"
          },
          {
            "name": "ACR Running for Canada FSI",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(ACR[Value]),ALLSELECTED(ACR[Month]),FILTER(ALLSELECTED(ACR[Month No]),ACR[Month No]<=MAX(ACR[Month No])))",
            "lineageTag": "1e50b564-6103-499e-9789-fdc40d376847"
          },
          {
            "name": "Canada_Qualified Pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM('Canada FSI Cohorts'[Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ac657f6f-0e1e-452a-828e-f3f00f33ca34"
          },
          {
            "name": "New Non Qualified (Running Canada FSI)",
            "expression": [
              "CALCULATE(",
              "                                      [Canada_Non Qualified Pipeline],",
              "                                      FILTER( ALL('Canada FSI Cohorts'[MonthName]),'Canada FSI Cohorts'[MonthName]<=MAX('Canada FSI Cohorts'[MonthName])))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "3cb2ba0a-9793-42ce-a785-f2675169113e"
          },
          {
            "name": "New_Qualified (Running Canada FSI)",
            "expression": [
              "CALCULATE(",
              "                                      [Canada_Qualified Pipeline],",
              "                                      FILTER( ALL('Canada FSI Cohorts'[MonthName]),'Canada FSI Cohorts'[MonthName]<=MAX('Canada FSI Cohorts'[MonthName])))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "141e1755-7c68-49ff-b32d-ea7af6c898d3"
          }
        ],
        "partitions": [
          {
            "name": "Canada FSI Cohorts-0260672f-7a6d-4a11-88db-77b6b49ade99",
            "mode": "import",
            "queryGroup": "Fact-Table",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\Stage 1 & 2 Pipeline Data\\Canada FSI\\May 22nd - Canada FSI Pipeline.xlsx\"), null, true),",
                "    Table1_Table = Source{[Item=\"Export\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Table1_Table, [PromoteAllScalars=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Promoted Headers\",{ {\"As of \", \"Date\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed Columns\",{\"Translated Account\", \"TPID\", \"Opportunity Name\", \"Qualified Pipeline\", \"Non-Qualified Pipeline\", \"Committed Pipeline\", \"Uncommitted Pipeline\", \"Sales Stage\", \"Est. Start Date\", \"Est. Completion Date\", \"SubRegion\", \"Subsidiary\", \"Industry\", \"Date\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Other Columns\",{{\"Date\", type date}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Canada_FSI_BDM",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "# Stakeholder Map",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3fbc59d-f315-420f-b006-09625380641b",
            "sourceColumn": "# Stakeholder Map",
            "summarizeBy": "sum"
          },
          {
            "name": "# of Contacts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "814bc802-a990-4c8c-bc6d-55e370245d1f",
            "sourceColumn": "# of Contacts",
            "summarizeBy": "sum"
          },
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4057a288-0407-42ec-a567-f646c050b8d9",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "96d1de28-5b33-4081-b388-6446daadb33f",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Dates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Canada_FSI_BDM'[Date],\"mmmm-dd-yyyy\")",
            "isDataTypeInferred": true,
            "lineageTag": "dbf03b80-41d3-45a0-aa06-7df4be1199b8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "IT BDMs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9d80da2d-9652-414d-b9ab-20e7b11bf486",
            "sourceColumn": "IT BDMs",
            "summarizeBy": "sum"
          },
          {
            "name": "Non IT BDMs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3818fd0a-2d1b-49a6-a7d4-d63bb4bcb1e8",
            "sourceColumn": "Non IT BDMs",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "8c114354-a356-48ac-8f02-86af93cdb55a",
        "measures": [
          {
            "name": "IT BDMs Canada FSI updated",
            "expression": "CALCULATE(SUM('Canada_FSI_BDM'[IT BDMs]))",
            "formatString": "0",
            "lineageTag": "52cd1e1a-e5de-4266-bbab-da489ae55143"
          },
          {
            "name": "Non IT BDMs Canada FSI updated",
            "expression": "CALCULATE(SUM('Canada_FSI_BDM'[Non IT BDMs]))",
            "formatString": "0",
            "lineageTag": "cf9b4b1a-1a63-4ada-a95f-9b04c24f65af"
          }
        ],
        "partitions": [
          {
            "name": "Canada_FSI_BDM-1fc04b8c-d56f-4d5d-a373-2af5feb1dc5c",
            "mode": "import",
            "queryGroup": "Fact-Table",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\BDM Data\\BDM by Cohorts_Master.xlsx\"), null, true),",
                "    #\"Canada FSI_Sheet\" = Source{[Item=\"Canada FSI\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Canada FSI_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type text}, {\"As of April 5th\", type any}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"As of May 16\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column6\"}),",
                "    #\"Promoted Headers1\" = Table.PromoteHeaders(#\"Removed Columns\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"Column1\", type text}, {\"# Stakeholder Map\", Int64.Type}, {\"# of Contacts\", Int64.Type}, {\"Non IT BDMs\", Int64.Type}, {\"Date of Data Pull\", type date}, {\"# Stakeholder Map_1\", Int64.Type}, {\"# of Contacts_2\", Int64.Type}, {\"Non IT BDMs_3\", Int64.Type}, {\"Date of Data Pull_4\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"Column1\", \"Account Name\"}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns\",{\"# Stakeholder Map_1\", \"# of Contacts_2\", \"Non IT BDMs_3\", \"Date of Data Pull_4\"}),",
                "    #\"Appended Query\" = Table.Combine({#\"Removed Columns1\", #\"Canada FSI-BDM-16May\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Appended Query\", each ([Account Name] <> null)),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Filtered Rows\",{{\"Date of Data Pull\", \"Date\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns1\", \"IT BDMs\", each [#\"# of Contacts\"]-[Non IT BDMs]),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"IT BDMs\", Int64.Type}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a1c10627-e46e-43ea-b712-85ea8ad931f5",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Created month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Date'[Date],\"mmmm, yyyy\")",
            "isDataTypeInferred": true,
            "lineageTag": "eeb07678-b21c-4edb-be12-1fc510cdd084",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3e50d187-30f0-439b-8a66-d7f6aee3a2ec",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3822d13c-7d86-403a-bcf6-6646d6f66cbe"
                },
                "isDefault": true,
                "relationship": "bc7e612c-2a01-43fe-b5e9-fb9b492ab3b0"
              }
            ]
          },
          {
            "name": "Date_New",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Date'[Date],\"mmmm-dd-yyyy\")",
            "lineageTag": "643114a0-83ca-4508-84af-1ecd66e8334a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day of Week Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fccbb9c2-a40a-41ff-a0de-4367980da7aa",
            "sourceColumn": "Day of Week Name",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "37d00f5e-c6e3-4720-aab9-68d8fa470926",
            "sourceColumn": "Day of Week Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Initials",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7bb2c5a-bee3-48a0-ab44-8ef0638447cd",
            "sourceColumn": "Month Initials",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "45d45163-dcb0-4f59-9796-151ee8870ff4",
            "sortByColumn": "Month Number",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "863f1373-00bc-4a52-ab0b-07b40d577ebd",
            "sourceColumn": "Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc871bb4-ef8d-4ed7-b6e8-a01610406ec8",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a738e3ca-7438-459c-afad-06a67bb9b553",
            "sourceColumn": "Quarter Number",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c9fa7bf3-c16d-4e44-9cad-eb47ce498621",
        "partitions": [
          {
            "name": "Date-8349485f-8940-4b4a-bc64-6f572540d38a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "",
                " // The column from which you want to build the date table",
                "",
                " Dates =",
                "",
                " let",
                "",
                " MinDate = #date(2023,01,01),",
                "",
                " MaxDate = #date(2023,12,31),",
                "",
                " StartDate = #date ( Date.Year ( MinDate ), 1, 1 ), // used -1 to get previous year",
                "",
                " EndDate = #date ( Date.Year ( MaxDate ) , 12, 31 ), // used + 1 to get the next year",
                "",
                " StartDateAsNumber = Number.From ( StartDate ),",
                "",
                " EndDateAsNumber = Number.From ( EndDate ),",
                "",
                " DateList = { StartDateAsNumber .. EndDateAsNumber },",
                "",
                " ToTable = Table.FromList (",
                "",
                " DateList,",
                "",
                " Splitter.SplitByNothing(),",
                "",
                " null,",
                "",
                " null,",
                "",
                " ExtraValues.Error",
                "",
                " ),",
                "",
                " RenameColumn = Table.RenameColumns ( ToTable, { \"Column1\", \"Date\" } ),",
                "",
                " ToDate = Table.TransformColumnTypes ( RenameColumn, { \"Date\", type date } )",
                "",
                " in",
                "",
                " ToDate,",
                "",
                " MonthName = Table.AddColumn (",
                "",
                " Dates,",
                "",
                " \"Month Name\",",
                "",
                " each Date.MonthName ( [Date] ),",
                "",
                " type text",
                "",
                " ),",
                "",
                " MonthNumber = Table.AddColumn (",
                "",
                " MonthName,",
                "",
                " \"Month Number\",",
                "",
                " each Date.Month ( [Date] ),",
                "",
                " Int64.Type",
                "",
                " ),",
                "",
                " CalendarYear = Table.AddColumn (",
                "",
                " MonthNumber,",
                "",
                " \"Calendar Year\",",
                "",
                " each Date.Year ( [Date] ),",
                "",
                " Int64.Type",
                "",
                " ),",
                "",
                " DayName = Table.AddColumn (",
                "",
                " CalendarYear,",
                "",
                " \"Day of Week Name\",",
                "",
                " each Date.DayOfWeekName ( [Date] ),",
                "",
                " type text",
                "",
                " ),",
                "",
                " DayNumber = Table.AddColumn (",
                "",
                " DayName,",
                "",
                " \"Day of Week Number\",",
                "",
                " each Date.Day ( [Date] ),",
                "",
                " Int64.Type",
                "",
                " ),",
                "",
                " MonthShortName = Table.AddColumn (",
                "",
                " DayNumber,",
                "",
                " \"Month Initials\",",
                "",
                " each Text.Start ( Date.MonthName ( [Date] ), 3 ),",
                "",
                " type text",
                "",
                " ),",
                "",
                " QuarterName = Table.AddColumn (",
                "",
                " MonthShortName,",
                "",
                " \"Quarter\",",
                "",
                " each \"Q\" & Text.From ( Date.QuarterOfYear ( [Date] ) ),",
                "",
                " type text",
                "",
                " ),",
                "",
                " QuarterNumber = Table.AddColumn (",
                "",
                " QuarterName,",
                "",
                " \"Quarter Number\",",
                "",
                " each Date.QuarterOfYear ( [Date] ),",
                "",
                " Int64.Type",
                "",
                " )",
                "",
                "in",
                "",
                " QuarterNumber"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_453ddd0e-2e9e-4474-94bd-704eb9bcd4b3",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "06c2e5e5-c7e4-4f94-abc4-c06ec4dc6534",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b814086c-8e90-484e-aa3a-13a2142fee69",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f37ac056-800f-4190-8571-df05dd76fd27",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ea3551bc-bde0-4833-92ad-223119f08c03",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6a51cbac-5e00-496f-8fdd-4d3c45ed63a6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "45f1aa18-23df-4804-bc57-d45d5a5a5091",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "80eb3abd-b538-45d6-b54b-d1194b78ebcf",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "52f287a7-9353-47e7-9afe-c6f48d221a96",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "39273859-cdda-4a2e-be40-26fef31b4708",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3e1bd682-c2cd-4322-8db6-d98f5272a3ff",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "82fc825c-5b5f-485e-8635-74d6d6e69bbf",
                "ordinal": 3
              }
            ],
            "lineageTag": "69987c41-a466-48cc-be4e-94dd78a43c6a"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "9f4f1d28-88b0-4ee2-abcf-e79601054a66",
        "partitions": [
          {
            "name": "DateTableTemplate_453ddd0e-2e9e-4474-94bd-704eb9bcd4b3-6c9573c7-5ff0-4fea-9012-fb8eda84ab3d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2229f48f-9f2a-4de4-bc1a-b9a27b7c9796",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "573e66d6-d263-487a-ae45-a410d4d71df5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "429c8bec-7d59-49ce-af29-f8898ab73fbd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "36b83d9c-ddf0-44b5-8ad8-43b656d37c29",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "466cd7e2-a3d0-43dd-aecf-9ee1ecd0d719",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8a1b0a61-f570-451e-91b2-4b5dc3d78ea8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "47770f13-31a4-498f-90a9-96a7d215dde3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "82c3b482-2107-4804-9bc6-45f15be06e55",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ac8c80bc-a262-4c24-a771-792be7d4cbb3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6f955eea-3789-4f9b-b08e-48d394994b1b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "626f592e-e7b0-44e0-828a-1cafe71e7f2e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "54e8c809-aa69-49ac-825c-55aad1ce19dc",
                "ordinal": 3
              }
            ],
            "lineageTag": "d79c2922-bfac-40ee-967b-65dced4dcbf3"
          }
        ],
        "isHidden": true,
        "lineageTag": "ab41bff7-b230-4b1a-9ae8-1afa00581c0e",
        "partitions": [
          {
            "name": "LocalDateTable_2229f48f-9f2a-4de4-bc1a-b9a27b7c9796-0f31f24c-b5fe-495b-a242-987d32be75f2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Sell BY Design'[Date])), 1, 1), Date(Year(MAX('Sell BY Design'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_2ba381bf-04fa-46af-a844-f8c961d9e64e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0aa80638-59a1-4aa6-b6fb-028dbaf80ad0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7ea07a5e-d5d7-4f42-b3e0-e349b40de434",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "86df8760-9726-49f5-9cd1-d35bea581b9a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bba99104-db5e-4fcb-a2c5-e0a6798c6bec",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1ee9c432-acbf-4814-8a6d-6785b656b0d2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5f6e5df9-c0b0-4e87-ad10-dec4bb0739ba",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "de4df6cc-8bc9-4a73-b857-eb72e42f1ffb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2d5f3947-5e66-4c60-b73f-c3630a4b2540",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ef951bef-3926-40b8-83da-c3248d57a39b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "aaa20210-16bd-4e1a-8c3d-9ace4d8dc023",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9efd6957-c959-4d7f-8687-7d99ff72f865",
                "ordinal": 3
              }
            ],
            "lineageTag": "ad37b5bd-1b88-4575-897f-7f93545dd62d"
          }
        ],
        "isHidden": true,
        "lineageTag": "12e9a162-0005-44e1-bbaf-91a895b410cc",
        "partitions": [
          {
            "name": "LocalDateTable_2ba381bf-04fa-46af-a844-f8c961d9e64e-6a9fa30e-c408-4cca-b2c1-ea384f5f1720",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('WECohort'[Est. Start Date])), 1, 1), Date(Year(MAX('WECohort'[Est. Start Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_3822d13c-7d86-403a-bcf6-6646d6f66cbe",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "45db4505-1e18-4387-858b-a2e4ca6999b5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9780d89c-2a0f-4876-bf06-b13e66c31092",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "efb473e6-1fc0-4113-83fa-d85b67a9dacc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d3260137-0f4a-4035-a9b7-c4f5f1ef9856",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ff6709a2-8ffe-4415-ad46-325f0725eeeb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "dc788f39-65bd-4bd7-8df2-9ab89b3ed54f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3c456cd9-0a63-4c4d-975b-9f308904f2b7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d3d541fe-d772-4a42-99e5-b3468d352c37",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a01c6776-f471-4cf4-b0ed-30d6536aaf7d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "692c9cbd-fd1d-469a-8e43-1c1aefcb7ea7",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a1209405-4611-4255-8918-281868f75320",
                "ordinal": 3
              }
            ],
            "lineageTag": "9d7b4005-0391-420c-b6e9-8dd9b560f5a5"
          }
        ],
        "isHidden": true,
        "lineageTag": "913df424-8447-4ce2-9fef-94ff192617c7",
        "partitions": [
          {
            "name": "LocalDateTable_3822d13c-7d86-403a-bcf6-6646d6f66cbe-845f60b4-4283-4c0e-aa72-bee1841b5b22",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date'[Date])), 1, 1), Date(Year(MAX('Date'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a2335a29-0813-43ca-8d8a-b50eae7ca3d2",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cbf607b5-8cf1-4e60-869e-64128fb8c197",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bab4a829-5e31-4815-b1b2-f2bbd503593c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "33c78855-8296-4894-8aae-bce0b74169bb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f236b4ec-7e36-46d9-855b-045e71116d4d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "37130cbd-8318-40c7-b4b8-964e472cb711",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e51ae249-61f4-4126-acdc-26026e0d3aab",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ae88c07e-643a-4a26-893e-68101172b1e2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "732ad74b-c3d1-4c57-a8eb-f6e1e4536dd9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "872de3d0-caad-415f-b88a-12e973d511bb",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9c6f185f-6123-4f5c-a7a5-0b33a5b17147",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "edb1009a-2ac1-44fc-b522-e9aaf0a72e10",
                "ordinal": 3
              }
            ],
            "lineageTag": "fdc478d7-f2c1-4c01-95b8-b702a2d33836"
          }
        ],
        "isHidden": true,
        "lineageTag": "22b1eee3-0d88-41fc-af23-22da84b50938",
        "partitions": [
          {
            "name": "LocalDateTable_a2335a29-0813-43ca-8d8a-b50eae7ca3d2-ea45794b-a1bf-4e5c-898a-6b26c37a1227",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('WECohort'[Est. Completion Date])), 1, 1), Date(Year(MAX('WECohort'[Est. Completion Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Sell BY Design",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "5/18 Notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5c2cf45-d582-4c71-a647-7d23a180eb36",
            "sourceColumn": "5/18 Notes",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f164a307-9d40-4e36-b560-d9e8f5151824",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name on ACR raw data list",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff5302b7-1bf4-41a6-84c8-98d531eb005d",
            "sourceColumn": "Account Name on ACR raw data list",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name on BDM raw data list",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2702eb8-b6fe-4cc4-aa8f-5ebb88596fa5",
            "sourceColumn": "Account Name on BDM raw data list",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name on Pipeline raw data list",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d70520e4-a778-474b-8576-0e7ebcc49e4b",
            "sourceColumn": "Account Name on Pipeline raw data list",
            "summarizeBy": "none"
          },
          {
            "name": "Cohort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70f11571-b233-4653-93ec-a8a17e44d74d",
            "sourceColumn": "Cohort",
            "summarizeBy": "none"
          },
          {
            "name": "Custom",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fcf1d74d-0ac2-4ba7-a100-62d1c894ec71",
            "sourceColumn": "Custom",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": "DATE(2023,05,05)",
            "formatString": "Long Date",
            "isDataTypeInferred": true,
            "lineageTag": "8b7f178d-f418-4dfd-9695-55dff0c0d194",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2229f48f-9f2a-4de4-bc1a-b9a27b7c9796"
                },
                "isDefault": true,
                "relationship": "57dd107a-5c90-4ef9-a506-f16d0dff3a72"
              }
            ]
          },
          {
            "name": "Len of Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53e2aeec-b97b-4f20-a39e-d7342471a5e8",
            "sourceColumn": "Len of Account",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7209a1eb-1fe4-4c73-97a8-b1eeeaa14463",
        "partitions": [
          {
            "name": "Sell BY Design-5190adcd-5689-4ddb-b48d-72ef4e959260",
            "mode": "import",
            "queryGroup": "Dimension",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\Account and Cohort List\\Sell By Design - Microsoft Accelerator FY23 Cohorts and Accounts.xlsx\"), null, true),",
                "    Table7_Table = Source{[Item=\"Table7\",Kind=\"Table\"]}[Data],",
                "    #\"Renamed Columns1\" = Table.RenameColumns(Table7_Table,{{\"Account Name (To Be Used in All Reporting)\", \"Account\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns1\", \"Len of Account\", each Text.Length([Account])),",
                "    #\"Inserted Text Before Delimiter\" = Table.AddColumn(#\"Added Custom\", \"Text Before Delimiter\", each Text.BeforeDelimiter([Account], \"\"), type text),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Inserted Text Before Delimiter\", \"Custom\", each Text.Length([Text Before Delimiter])),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Custom1\",{{\"Text Before Delimiter\", \"Account Name\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Account\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\", {\"Account Name\"}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Removed Duplicates\",{{\"Account Name\", Text.Trim, type text}}),",
                "    #\"Cleaned Text\" = Table.TransformColumns(#\"Trimmed Text\",{{\"Account Name\", Text.Clean, type text}})",
                "in",
                "    #\"Cleaned Text\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Summary",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "43e940cee9674e43b8fd0de61cb25eec"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c7f2e2fb-5767-4c38-b0a8-15fad703c473",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c294ef3a-4941-42c4-9007-00ca76e31aa3",
        "measures": [
          {
            "name": "Baseline Total IT BDMs For Cohorts",
            "expression": "CALCULATE([IT BDMs Canada FSI updated]+[Uk IT]+[IT BDMs WE]+[IT BDms canada E&R],'Date'[Date]=DATE(2023,04,17))",
            "formatString": "0",
            "lineageTag": "e12cf54e-658e-4c62-b675-a7f7be71045b"
          },
          {
            "name": "Current Total IT BDMs For Cohorts",
            "expression": "CALCULATE([IT BDMs Canada FSI updated]+[Uk IT]+[IT BDMs WE]+[IT BDms canada E&R],'Date'[Date]=DATE(2023,05,05)|| 'Date'[Date]=DATE(2023,05,16))",
            "formatString": "0",
            "lineageTag": "e9a2599d-6012-4cba-841b-83f48b1531d1"
          },
          {
            "name": "Baseline Total Non IT BDMs",
            "expression": "CALCULATE([Non IT BDMs Canada FSI updated]+[Non it Canada Er]+[NonIT BDM_WE]+[NonIT BDM_UK],'Date'[Date]=DATE(2023,04,17))",
            "formatString": "0",
            "lineageTag": "a6113c7a-a76c-4dac-ba04-45d4eab82fdf"
          },
          {
            "name": "Current Total Non IT BDMs",
            "expression": "CALCULATE([Non IT BDMs Canada FSI updated]+[Non it Canada Er]+[NonIT BDM_WE]+[NonIT BDM_UK],'Date'[Date]=DATE(2023,05,05)||'Date'[Date]=DATE(2023,05,16))",
            "formatString": "0",
            "lineageTag": "5cd83dea-f9d1-4b8c-aeca-5d97b780fd80"
          },
          {
            "name": "Total IT BDMs For Cohorts",
            "expression": "[IT BDMs Canada FSI updated]+[Uk IT]+[IT BDMs WE]+[IT BDms canada E&R]",
            "formatString": "0",
            "lineageTag": "7550770d-9020-446a-965e-4694b112cbc6"
          },
          {
            "name": "Total Non IT BDMs",
            "expression": "[Non IT BDMs Canada FSI updated]+[Non it Canada Er]+[NonIT BDM_WE]+[NonIT BDM_UK]",
            "formatString": "0",
            "lineageTag": "4b80d921-9866-4f04-8f64-23a00da7878d"
          },
          {
            "name": "Stage1 Baseline Summary",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE([Non_Qualified]+[Canada_Non Qualified Pipeline]+[We_non Qualified Pipeline],'Date'[Date]=DATE(2023,04,10)|| 'Date'[Date]=DATE(2023,04,18) )",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ddf05d2a-2245-45ca-b8ce-29bf1a3534f8"
          },
          {
            "name": "Stage1 Current  Summary",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE([Non_Qualified]+[Canada_Non Qualified Pipeline]+[We_non Qualified Pipeline],'Date'[Date]=DATE(2023,05,22) )",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "9c434442-2ac4-453c-9e3a-76cce4f8a03d"
          },
          {
            "name": "Stage 2 Baseline Summary",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE([Qualified_Pipeline_UK]+[Canada_Qualified Pipeline]+[We_Qualified Pipeline],'Date'[Date]=DATE(2023,04,10)|| 'Date'[Date]=DATE(2023,04,18))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a92bb18f-75f7-4f5d-8272-09a83baa3bb6"
          },
          {
            "name": "Stage 2 Current Summary",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE([Qualified_Pipeline_UK]+[Canada_Qualified Pipeline]+[We_Qualified Pipeline],'Date'[Date]=DATE(2023,05,22))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "de47460f-f1be-4c5e-afc4-1ce20d9b0833"
          },
          {
            "name": "Running Stage2 RollUp Avg",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var last =CALCULATE([Stage 2 Rollup],FILTER(ALL('Date'[Date]),'Date'[Date]<=max('Date'[Date])))",
              "                           var fs = CALCULATE([Stage 2 Rollup],FILTER(ALL('Date'[Date]),'Date'[Date]<=max('Date'[Date])-1))",
              "                           return",
              "                           DIVIDE((last-fs),fs)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3536b4d9-4c30-4331-8f08-41d43d3fba3a"
          },
          {
            "name": "Running Stage2 RollUp",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "/* CALCULATE([Stage 2 Rollup],FILTER(ALL('Date'[Date]),'Date'[Date]<=max('Date'[Date]))) */",
              "                        CALCULATE([Stage 2 Rollup],FILTER(ALL('Date'[Month Number]),'Date'[Month Number]<=max('Date'[Month Number])),ALL('Date'[Month Name]))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c0b79d75-71f1-4a97-8cff-fe610adae2b4"
          },
          {
            "name": "Running Stage1 roll up",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE([Stage 1 roll up],FILTER( ALL('Date'[Date]),'Date'[Date]<=MAX('Date'[Date])    /* ,CROSSFILTER('Canada FSI Cohorts 17 April'[DATE],'Date'[Date],Both),CROSSFILTER('WECohort 17 April'[Date],'Date'[Date],Both),CROSSFILTER('Date'[Date],'UK Cohorts 17 April'[Date],Both) )  */))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "fb217e38-f064-460d-a2dc-4170f44a2665"
          },
          {
            "name": "Running Stage1 roll up Avg",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var last = CALCULATE([Stage 1 roll up],FILTER( ALL('Date'[Date]),'Date'[Date]<=MAX('Date'[Date])))",
              "                              var FS= CALCULATE([Stage 1 roll up],FILTER( ALL('Date'[Date]),'Date'[Date]<=MAX('Date'[Date])-1))",
              "                               return",
              "                               DIVIDE((last-FS),FS)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3348a300-c2c0-460e-bc16-9eba33b9fc4e"
          },
          {
            "name": "Stage 1 roll up",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[New Non Qualified pipeline uk]+[Canada_Non Qualified Pipeline]+[We_non Qualified Pipeline]/*  [Non Qualified (Running Canada FSI)]+[Non Qualified (Running UK)]+[Non Qualified (Running WE Cohort FSI)] */",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "af76f43c-9d7a-4ea3-b1c0-82fca8b1527a"
          },
          {
            "name": "Stage 2 Rollup",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "/* [Qualified_Pipeline_UK] */+[Canada_Qualified Pipeline]+[We_Qualified Pipeline]+[New Qualified pipeline uk]",
            "lineageTag": "faaaee37-f79a-4a16-b271-9902696c583b"
          },
          {
            "name": "BDM_Color code",
            "expression": "SWITCH(SELECTEDVALUE('Date'[Date]),DATE(2023,04,17),\"FF8420\",DATE(2023,05,05),\"#E75542\")",
            "lineageTag": "377aefdf-6869-46ed-99c4-315812c3e0b2"
          },
          {
            "name": "Summary ACR Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(ACR[Value])  ,USERELATIONSHIP(ACR[Account],'UK_Cohorts'[Translated Account])  )",
            "lineageTag": "536c1520-f872-4ea5-931d-6a54308d47c2"
          },
          {
            "name": "Final",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM(ACR[Value])+[Summary ACR Value]+[WE Cohort ACR Value])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f91dbbd1-275d-459f-a7e4-5d0b236901a3"
          },
          {
            "name": "Total Baseline",
            "expression": "[Baseline Total IT BDMs For Cohorts]+[Baseline Total Non IT BDMs]",
            "formatString": "0",
            "lineageTag": "5b7399eb-4bbb-4379-be76-cf6f552ef7fd"
          },
          {
            "name": "Current Total",
            "expression": "[Current Total IT BDMs For Cohorts]+[Current Total Non IT BDMs]",
            "formatString": "0",
            "lineageTag": "39c836ef-9f4f-46dd-9681-7a5f36e30143"
          },
          {
            "name": "Color code summary acr",
            "expression": [
              "SWITCH(SELECTEDVALUE(ACR[Baseline&Current]),\"baseline\",\"#FF8420\",\"Current Month\",\"#E75542\")",
              "                        "
            ],
            "lineageTag": "77bdd5eb-587c-4e4f-902a-80f43f43f885"
          },
          {
            "name": "Color code summary acr uk",
            "expression": "CALCULATE( SWITCH(SELECTEDVALUE(ACR[Baseline&Current]),\"baseline\",\"#FF8420\",\"Current Month\",\"#E75542\"),USERELATIONSHIP(ACR[Account],'UK_Cohorts'[Translated Account]))",
            "lineageTag": "48a769ae-4800-42ff-871e-53753130be53"
          },
          {
            "name": "Color code summary acr we",
            "expression": "CALCULATE( SWITCH(SELECTEDVALUE(ACR[Baseline&Current]),\"baseline\",\"#FF8420\",\"Current Month\",\"#E75542\"),USERELATIONSHIP(ACR[Account],'WECohort'[Translated Account]))",
            "lineageTag": "e90460ed-5d2d-44dc-b702-15c434540779"
          },
          {
            "name": "Final color code ACR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Color code summary acr]+[Color code summary acr uk]+[Color code summary acr we]",
            "lineageTag": "b7a03f6f-3725-426e-bf3c-01de01b9f428"
          },
          {
            "name": "Current Total Non IT BDMs Dynamic",
            "expression": "CALCULATE([Non IT BDMs Canada FSI updated]+[Non it Canada Er]+[NonIT BDM_WE]+[NonIT BDM_UK],'Date'[Date]=MAX('UK BDMs'[Date of Data Pull]) || 'Date'[Date]=MAX(Canada_FSI_BDM[Date]) || 'Date'[Date]=MAX(WE_BDM[Date]) || 'Date'[Date] = MAX('Canada E&R-BDM'[Date]))",
            "formatString": "0",
            "lineageTag": "337b0bf6-fe72-465a-85da-418784e06dd9"
          },
          {
            "name": "Current Total IT BDMs For Cohorts Dynamic",
            "expression": "CALCULATE([IT BDMs Canada FSI updated]+[Uk IT]+[IT BDMs WE]+[IT BDms canada E&R],'Date'[Date]=MAX('UK BDMs'[Date of Data Pull]) || 'Date'[Date]=MAX(Canada_FSI_BDM[Date]) || 'Date'[Date]=MAX(WE_BDM[Date]) || 'Date'[Date] = MAX('Canada E&R-BDM'[Date]))",
            "formatString": "0",
            "lineageTag": "ac49870f-d425-49f0-a96f-0b9d134eb9f3"
          },
          {
            "name": "Current Total Dynamic",
            "expression": "[Current Total Non IT BDMs Dynamic]+[Current Total IT BDMs For Cohorts Dynamic]",
            "formatString": "0",
            "lineageTag": "49cef2f8-0f10-4882-ae00-fa8ca9f7cc2e"
          },
          {
            "name": "Baseline Total Non IT BDMs Dynamic",
            "expression": [
              "CALCULATE([Non IT BDMs Canada FSI updated]+[Non it Canada Er]+[NonIT BDM_WE]+[NonIT BDM_UK],",
              "                                'Date'[Date]=MIN('UK BDMs'[Date of Data Pull]) ||'Date'[Date]=Min(Canada_FSI_BDM[Date]) || ",
              "                             'Date'[Date]=MIN(WE_BDM[Date])|| 'Date'[Date]=MIN('Canada E&R-BDM'[Date])",
              "                            /*  'Date'[Date]<MAX('UK BDMs'[Date of Data Pull]) || 'Date'[Date]<MAX(Canada_FSI_BDM[Date]) ||'Date'[Date] */)"
            ],
            "formatString": "0",
            "lineageTag": "63c7bba4-d83e-4c6b-835a-5a283d593b12"
          },
          {
            "name": "Stage1 Current  Summary Dynamic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Non_Qualified]+[Canada_Non Qualified Pipeline]+[We_non Qualified Pipeline],'Date'[Date]=max(UK_Cohorts[Date] )|| 'Date'[Date]=MAX(WECohort[Date])||'Date'[Date]=MAX('Canada FSI Cohorts'[Date]))",
            "lineageTag": "3abdfbd8-940b-4179-ae81-d5b5896ebb37"
          },
          {
            "name": "Stage1 Baseline Summary Dynamic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Non_Qualified]+[Canada_Non Qualified Pipeline]+[We_non Qualified Pipeline],'Date'[Date]=MIN(UK_Cohorts[Date])|| 'Date'[Date]=MIN(WECohort[Date])|| 'Date'[Date]=MIN('Canada FSI Cohorts'[Date] ))",
            "lineageTag": "3acf7cb5-7abe-4f7d-9e69-2809140e95b5"
          },
          {
            "name": "Stage 2 Baseline Summary Dynamic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Qualified_Pipeline_UK]+[Canada_Qualified Pipeline]+[We_Qualified Pipeline],'Date'[Date]=MIN(UK_Cohorts[Date])|| 'Date'[Date]=MIN(WECohort[Date])|| 'Date'[Date]=MIN('Canada FSI Cohorts'[Date]))",
            "lineageTag": "1976165b-75bf-49c6-a300-41914181c16f"
          },
          {
            "name": "Stage 2 Current Summary Dynamic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Qualified_Pipeline_UK]+[Canada_Qualified Pipeline]+[We_Qualified Pipeline],'Date'[Date]=MAX(UK_Cohorts[Date])|| 'Date'[Date]=MAX(WECohort[Date])|| 'Date'[Date]=MAX('Canada FSI Cohorts'[Date]))",
            "lineageTag": "53f9d8ba-0d1a-420c-ad65-f5507c0ac433"
          },
          {
            "name": "Baseline Total IT BDMs For Cohorts Dynamic",
            "expression": "CALCULATE([IT BDMs Canada FSI updated]+[Uk IT]+[IT BDMs WE]+[IT BDms canada E&R],'Date'[Date]=MIN('UK BDMs'[Date of Data Pull])|| 'Date'[Date]=MIN(Canada_FSI_BDM[Date])|| 'Date'[Date]=MIN(WE_BDM[Date])||'Date'[Date]=MIN('Canada E&R-BDM'[Date]))",
            "formatString": "0",
            "lineageTag": "87a8d903-2084-42ec-a96a-09d2b15cc99e"
          },
          {
            "name": "Total Baseline Dynamic",
            "expression": "[Baseline Total IT BDMs For Cohorts Dynamic]+[Baseline Total Non IT BDMs Dynamic]",
            "formatString": "0",
            "lineageTag": "9fa68a84-f38d-4654-90c3-4f4a70f0fe03"
          },
          {
            "name": "Test_Stage 1 roll up",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Non_Qualified]+[Canada_Non Qualified Pipeline]+[We_non Qualified Pipeline] /* [Non Qualified (Running Canada FSI)]+[Non Qualified (Running UK)]+[Non Qualified (Running WE Cohort FSI)] */",
            "lineageTag": "ccf89223-41b5-4a93-9ddd-adb44a70c924"
          },
          {
            "name": "newtest_Stage 1 roll up",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Non_Qualified]+[Canada_Non Qualified Pipeline]+[We_non Qualified Pipeline] ",
            "lineageTag": "5896c39c-5ada-4f7e-886b-524faefba741"
          },
          {
            "name": "Test Stage 2 rollup",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Qualified (Running Canada FSI)]+[Qualified (Running UK)]+[Qualified (Running WE Cohort FSI)]",
            "lineageTag": "ffb80ba9-e237-4be3-a2de-46633012f66f"
          },
          {
            "name": "New Qualified pipeline uk",
            "expression": "CALCULATE([Qualified_Pipeline_UK],USERELATIONSHIP(UK_Cohorts[Created Month],'Date'[Created month]),CROSSFILTER('Date'[Date],UK_Cohorts[Date],None),UK_Cohorts[Month no]>\"3\"&&UK_Cohorts[Month no]<>BLANK())",
            "formatString": "0",
            "lineageTag": "b1206c46-be3a-4f12-be0e-886fb596ebfb"
          },
          {
            "name": "New Non Qualified pipeline uk",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Non_Qualified],USERELATIONSHIP(UK_Cohorts[Created Month],'Date'[Created month]),CROSSFILTER('Date'[Date],UK_Cohorts[Date],None),UK_Cohorts[Month no]>\"3\"&&UK_Cohorts[Month no]<>BLANK())",
            "lineageTag": "f6dd1029-ed9f-4789-85c0-28a90dd19b4c"
          }
        ],
        "partitions": [
          {
            "name": "Summary-b0339c1f-15d0-4258-8cd4-2027949e301d",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "UK BDMs",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "# Stakeholder Map",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4cb5d11e-a002-4e6b-9917-a5fcf6291a9a",
            "sourceColumn": "# Stakeholder Map",
            "summarizeBy": "sum"
          },
          {
            "name": "# of Contacts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8170ae35-0c7d-4be5-a92b-2bb2d3f7b5be",
            "sourceColumn": "# of Contacts",
            "summarizeBy": "sum"
          },
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c41ef6e-39fe-49af-b012-66bfdeb09c4a",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('UK BDMs'[Date of Data Pull],\"mmmm-dd-yyyy\")",
            "isDataTypeInferred": true,
            "lineageTag": "f08faa22-012a-457a-a5bf-b64c92ba6b39",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date of Data Pull",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6c16b60a-09e8-4427-9d38-9c07aa2a21e2",
            "sourceColumn": "Date of Data Pull",
            "summarizeBy": "none"
          },
          {
            "name": "Difference",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'UK BDMs'[Non IT BDMs]-'UK BDMs'[IT BDMs]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9a1ef107-934a-49a8-9203-7f31191215d7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "IT BDMs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'UK BDMs'[# of Contacts] - 'UK BDMs'[Non IT BDMs]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "35eb5e05-14aa-476b-a57a-5255eea2ac46",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Non IT BDMs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27efc55f-a58d-4e3c-b2d5-c254ee95c19d",
            "sourceColumn": "Non IT BDMs",
            "summarizeBy": "sum"
          },
          {
            "name": "TPID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1469264a-1ace-40b9-8a4b-f0cb3d1d4a57",
            "sourceColumn": "TPID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "0615d7e1-39c3-4dd6-851d-04170c139202",
        "measures": [
          {
            "name": "Uk Non IT",
            "expression": "CALCULATE(SUM('UK BDMs'[Non IT BDMs]))",
            "formatString": "0",
            "lineageTag": "82c4186d-33be-4fb9-9f3f-25fa9e3a2716"
          },
          {
            "name": "Uk IT",
            "expression": "CALCULATE(SUM('UK BDMs'[IT BDMs]))",
            "formatString": "0",
            "lineageTag": "db0664e6-23e3-4336-8aae-2a00f1779802"
          },
          {
            "name": "NonIT BDM_UK",
            "expression": "CALCULATE(SUM('UK BDMs'[Non IT BDMs]))",
            "formatString": "0",
            "lineageTag": "71b1b67b-4ec7-4594-a297-82347a91cbe8"
          }
        ],
        "partitions": [
          {
            "name": "UK BDMs-0453fd53-69ff-4280-9c8b-f41181692d8f",
            "mode": "import",
            "queryGroup": "Fact-Table",
            "source": {
              "expression": [
                "let",
                "    Source = #\"uk bdm 23may\",",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(Source,{{\"TPID\", Int64.Type}, {\"# Stakeholder Map\", Int64.Type}, {\"# of Contacts\", Int64.Type}, {\"Non IT BDMs\", Int64.Type}}),",
                "    #\"Cleaned Text\" = Table.TransformColumns(#\"Changed Type1\",{{\"Account Name\", Text.Clean, type text}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Cleaned Text\",{{\"Account Name\", Text.Trim, type text}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Trimmed Text\", each ([TPID] <> null)),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Filtered Rows1\",{{\"Date of Data Pull\", type date}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "UK_Cohorts",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Committed Pipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ab4b08e-e68a-4053-9d80-d69eae2a2a45",
            "sourceColumn": "Committed Pipeline",
            "summarizeBy": "none"
          },
          {
            "name": "Created Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9fb365d8-dc75-4ee5-b6a1-84ac49b45632",
            "sourceColumn": "Created Month",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd mmmm yyyy",
            "lineageTag": "19179d2e-51f1-4c1b-a721-5838fa2a0c53",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Date_new",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('UK_Cohorts'[Date],\"mmmm-dd-yyyy\")",
            "isDataTypeInferred": true,
            "lineageTag": "e2ca161d-86e4-42db-8e2c-2dde7d2fcb86",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Days in Sales Stage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "92191da6-5a42-4714-ba59-b702c7666c14",
            "sourceColumn": "Days in Sales Stage",
            "summarizeBy": "sum"
          },
          {
            "name": "Days in Sales Stage Age Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd6b87a4-4da2-4efd-a231-23f85224d5c3",
            "sourceColumn": "Days in Sales Stage Age Group",
            "summarizeBy": "none"
          },
          {
            "name": "EvenOdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(TRUE(),",
              "    'UK_Cohorts'[Created Month] = \"April, 2023\" || 'UK_Cohorts'[Created Month] = \"June, 2023\" ||",
              "    'UK_Cohorts'[Created Month] = \"August, 2023\" || 'UK_Cohorts'[Created Month] = \"October, 2023\" ||",
              "    'UK_Cohorts'[Created Month] = \"December, 2023\", \"Even\",",
              "    'UK_Cohorts'[Created Month] = \"January, 2023\" || 'UK_Cohorts'[Created Month] = \"March, 2023\" ||",
              "    'UK_Cohorts'[Created Month] = \"May, 2023\" || 'UK_Cohorts'[Created Month] = \"July, 2023\" ||",
              "    'UK_Cohorts'[Created Month] = \"September, 2023\", \"Odd\",",
              "    \"None\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "92dad554-275c-4239-9b1b-b1cc10a01cf8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "IF(UK_Cohorts[Date]<>BLANK()&&UK_Cohorts[Created Month]<>BLANK(),1,0",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "4c793127-3c59-44e5-a39c-bbd9c16e68de",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Industry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe3bc474-9192-414e-a91c-90f9a417f7d2",
            "sourceColumn": "Industry",
            "summarizeBy": "none"
          },
          {
            "name": "MACC Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6bb3d877-239c-4a1b-ab66-a827df235fd7",
            "sourceColumn": "MACC Account",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(UK_Cohorts[Created Month],\"mmmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "f8b4056e-0921-4d5e-b451-05f9ea6adabc",
            "sortByColumn": "Month no",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month no",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "expression": "MONTH(UK_Cohorts[Created Month])",
            "lineageTag": "1ea4e469-5911-4a4a-9090-72f67bb331ad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Non-Qualified Pipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1a0a5487-99ed-4bee-9aa0-8806da70645f",
            "sourceColumn": "Non-Qualified Pipeline",
            "summarizeBy": "sum"
          },
          {
            "name": "Opportunity Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c17b870e-bb9a-4742-b2f8-3d68961d8cb2",
            "sourceColumn": "Opportunity Name",
            "summarizeBy": "none"
          },
          {
            "name": "Qualified Pipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0eaa03b0-fc97-4f96-b3bf-57f0d5233e26",
            "sourceColumn": "Qualified Pipeline",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales Stage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb40e8e3-e737-470e-bbc6-2bf160512a0c",
            "sourceColumn": "Sales Stage",
            "summarizeBy": "none"
          },
          {
            "name": "TPID.12.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8ff1dfa8-ce64-47ba-81b0-7be5b290a9d5",
            "sourceColumn": "TPID.12.1",
            "summarizeBy": "sum"
          },
          {
            "name": "Translated Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8427f2c0-6bb4-4038-91e3-da121bc17447",
            "sourceColumn": "Translated Account",
            "summarizeBy": "none"
          },
          {
            "name": "Uncommitted Pipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f39e00d4-fc51-4bd0-be5c-fa44313e9deb",
            "sourceColumn": "Uncommitted Pipeline",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2308b333-ae8c-4bbf-a8c1-e81fb28fbbfd",
        "measures": [
          {
            "name": "Qualified_Pipeline_UK",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM('UK_Cohorts'[Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "99aad406-3499-4f00-9512-efef71765261"
          },
          {
            "name": "Average_Qualified",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(AVERAGE('UK_Cohorts'[Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "8bdf5949-a764-4587-8dc7-92ef406828f4"
          },
          {
            "name": "Non_Qualified",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM('UK_Cohorts'[Non-Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "33398c7f-fdeb-4351-82b1-e4a7547cbc45"
          },
          {
            "name": "Non Qualified (Running UK)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(",
              "                                      [Non_Qualified],",
              "                                      FILTER( ALL('UK_Cohorts'[Month no]),'UK_Cohorts'[Month no]<=MAX('UK_Cohorts'[Month no])),UK_Cohorts[Month no]>\"3\" & UK_Cohorts[Month no]<>BLANK(),ALL(UK_Cohorts[Month Name]",
              "))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "00857047-b20f-4613-9ae2-181291341859"
          },
          {
            "name": "Qualified (Running UK)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(",
              "                                      [Qualified_Pipeline_UK],",
              "                                      FILTER( ALL('UK_Cohorts'[Month no]),'UK_Cohorts'[Month no]<=MAX('UK_Cohorts'[Month no])),UK_Cohorts[Month no]>\"3\" & UK_Cohorts[Month no]<>BLANK(),ALL(UK_Cohorts[Month Name]))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "df2aae8c-d2d4-482d-aa6c-82b8b1ec9441"
          },
          {
            "name": "color code UK",
            "expression": [
              "",
              "",
              "SWITCH(",
              "",
              " SELECTEDVALUE('Sell BY Design'[Account Name]),",
              "",
              " \"ASSOCIATED BRITISH FOODS PLC\",\"#FF8420\",",
              "",
              "\"BAKKAVOR FOODS LTD\",\"#E75542\",",
              "",
              " \"BURBERRY GROUP LTD\",\"#FF8420\",",
              "",
              "\"MARKS & SPENCER PLC\",\"#E75542\",",
              "",
              "\"MERLIN ENTERTAINMENT SEA LIFE LTD\",\"#FF8420\",",
              "",
              "\"NEXT PLC\",\"#E75542\",",
              "",
              "\"Ocado\",\"#FF8420\",",
              "",
              "\"PENTLAND GROUP PLC\",\"#E75542\",",
              "",
              "\"RANK GROUP PLC\",\"#FF8420\",",
              "",
              "\"SAINSBURYS\",\"#E75542\",",
              "",
              "\"SPECSAVERS OPTICAL SUPERSTORES LTD\", \"#FF8420\")",
              "",
              ""
            ],
            "lineageTag": "83fc0760-7e5f-4b69-a91d-c7d92b30a6a2"
          },
          {
            "name": "UK Stage 1 for Baseline",
            "expression": "CALCULATE([Non_Qualified],'UK_Cohorts'[Date]=date(2023,04,17))",
            "formatString": "0",
            "lineageTag": "0ea21aef-bc20-4e6e-aed7-781f6a54d685"
          },
          {
            "name": "Uk Stage 1 for Current",
            "expression": "CALCULATE([Non_Qualified],'UK_Cohorts'[Date]=DATE(2023,05,05))",
            "formatString": "0",
            "lineageTag": "af087bc0-38d2-4fe7-8acc-27734bec8b41"
          },
          {
            "name": "Difference In Stage1 uk",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([Uk Stage 1 for Current]-[UK Stage 1 for Baseline],[UK Stage 1 for Baseline])",
            "lineageTag": "313d5005-f4e0-4b36-8a9c-8deee0062527"
          },
          {
            "name": "UK Stage 2 For Baseline",
            "expression": "CALCULATE([Qualified_Pipeline_UK],'UK_Cohorts'[Date]=DATE(2023,04,17))",
            "formatString": "0",
            "lineageTag": "5126cc5b-3d25-4dc0-980f-71ca8b782e39"
          },
          {
            "name": "UK Stage 2 For Current",
            "expression": "CALCULATE([Qualified_Pipeline_UK],'UK_Cohorts'[Date] = DATE(2023,05,05))",
            "formatString": "0",
            "lineageTag": "51ea2a54-456d-4c5f-8a51-40a25d5456c8"
          },
          {
            "name": "Non Qualified (Running UK) Avg",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "             var Last =               CALCULATE(",
              "                                      [Non_Qualified],",
              "                                      FILTER( ALL('UK_Cohorts'[Date]),'UK_Cohorts'[Date]<=MAX('UK_Cohorts'[Date])))",
              "",
              "             var FS =                 CALCULATE(",
              "                                      [Non_Qualified],",
              "                                      FILTER( ALL('UK_Cohorts'[Date]),'UK_Cohorts'[Date]<=MAX('UK_Cohorts'[Date])-1)) ",
              "             Return",
              "             Divide((Last-fs),FS)                                                 "
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "097ad8c3-21a5-462c-83ce-3d460803bf3f"
          },
          {
            "name": "Qualified (Running UK) Avg",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "             var Last =               CALCULATE(",
              "                                      [Qualified_Pipeline_UK],",
              "                                      FILTER( ALL('UK_Cohorts'[Date]),'UK_Cohorts'[Date]<=MAX('UK_Cohorts'[Date])))",
              "",
              "             var FS =                 CALCULATE(",
              "                                      [Qualified_Pipeline_UK],",
              "                                      FILTER( ALL('UK_Cohorts'[Date]),'UK_Cohorts'[Date]<=MAX('UK_Cohorts'[Date])-1)) ",
              "             Return",
              "             Divide((Last-fs),FS)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "70375ce9-cd84-42db-8637-05dfa2158b47"
          },
          {
            "name": "UK_Color code",
            "expression": "SWITCH(SELECTEDVALUE('UK_Cohorts'[Date]),DATE(2023,04,18),\"#FF8420\")",
            "lineageTag": "c3133f00-755f-4a5c-be08-83c8341dc85b"
          },
          {
            "name": "UK ACR Value",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM(ACR[Value]),USERELATIONSHIP(ACR[Account],'UK_Cohorts'[Translated Account]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "89676a55-63b3-4e72-a03f-60a6d06b7c42"
          },
          {
            "name": "UK ACR Value running uk",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(ACR[Value]),USERELATIONSHIP('UK_Cohorts'[Translated Account],ACR[Account]) ,ALLSELECTED(ACR[Month]) ,FILTER(ALLSELECTED(ACR[Month No]),ACR[Month No]<=MAX(ACR[Month No])))",
            "lineageTag": "02b5a7a4-edb9-42d9-8c41-ca9c51893a62"
          },
          {
            "name": "test_Non Qualified (Running UK)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "                                      [Non_Qualified],",
              "                                      FILTER( ALL('UK_Cohorts'[Date_new]),'UK_Cohorts'[Date_new]<=MAX('UK_Cohorts'[Date_new])))"
            ],
            "lineageTag": "95af7d70-29c1-46e6-81e3-cf48dd2eeab8"
          },
          {
            "name": "alternate color UK",
            "expression": "CALCULATE(SWITCH(SELECTEDVALUE(UK_Cohorts[Month Name]),\"April, 2023\",\"#FF8420\",\"May, 2023\",\"#E75542\",\"June, 2023\",\"#FF8420\")) ",
            "lineageTag": "06e70cdf-44a8-4f75-9c93-26f28c44a218"
          }
        ],
        "partitions": [
          {
            "name": "UK_Cohorts-89d5cbe1-5ee6-4c45-9cac-951e88eceeca",
            "mode": "import",
            "queryGroup": "Fact-Table",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\Stage 1 & 2 Pipeline Data\\UK RCG\\UK Cohorts Weekly Pipeline 06.06.23.xlsx\"), null, true),",
                "    Table1_Table = Source{[Item=\"Export\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers1\" = Table.PromoteHeaders(Table1_Table, [PromoteAllScalars=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Promoted Headers1\",{{\"As of\", \"Date\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{ {\"MSX\", type text},{\"Translated Account\", type text}, {\"TPID\", type text}, {\"MACC Account\", type text}, {\"Opportunity Name\", type text}, {\"Qualified Pipeline\", type any}, {\"Non-Qualified Pipeline\", type number}, {\"Committed Pipeline\", type any}, {\"Uncommitted Pipeline\", type any}, {\"Days in Sales Stage Age Group\", type text}, {\"Days in Sales Stage\", Int64.Type}, {\"Opportunity Number\", type text}, {\"Sales Stage\", type text}, {\"Est. Start Date\", type date}, {\"Est. Completion Date\", type date}, {\"MCS Engaged Flag\", type text}, {\"Opportunity Owner\", type text}, {\"Preferred Azure Region\", type text}, {\"Partner Sharing Status\", type text}, {\"SubRegion\", type text}, {\"Subsidiary\", type text}, {\"Field Summary Segment\", type text}, {\"Industry\", type text}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Changed Type\", \"TPID\", Splitter.SplitTextByDelimiter(\"/\", QuoteStyle.Csv), {\"TPID.1\", \"TPID.2\", \"TPID.3\", \"TPID.4\", \"TPID.5\", \"TPID.6\", \"TPID.7\", \"TPID.8\", \"TPID.9\", \"TPID.10\", \"TPID.11\", \"TPID.12\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"TPID.1\", type text}, {\"TPID.2\", type text}, {\"TPID.3\", type text}, {\"TPID.4\", type text}, {\"TPID.5\", type text}, {\"TPID.6\", Int64.Type}, {\"TPID.7\", type text}, {\"TPID.8\", type text}, {\"TPID.9\", Int64.Type}, {\"TPID.10\", type text}, {\"TPID.11\", type text}, {\"TPID.12\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"TPID.1\", \"TPID.2\", \"TPID.3\", \"TPID.4\", \"TPID.5\", \"TPID.6\", \"TPID.7\", \"TPID.8\", \"TPID.9\", \"TPID.10\", \"TPID.11\"}),",
                "    #\"Split Column by Delimiter1\" = Table.SplitColumn(#\"Removed Columns\", \"TPID.12\", Splitter.SplitTextByDelimiter(\"&\", QuoteStyle.Csv), {\"TPID.12.1\", \"TPID.12.2\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Split Column by Delimiter1\",{{\"TPID.12.1\", Int64.Type}, {\"TPID.12.2\", type text}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type2\",{\"TPID.12.2\"}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Removed Columns1\",{{\"Date\", type date}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type3\", each ([Translated Account] <> null)),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\",{\"Translated Account\", \"TPID.12.1\", \"MACC Account\", \"Opportunity Name\", \"Qualified Pipeline\", \"Non-Qualified Pipeline\", \"Committed Pipeline\", \"Uncommitted Pipeline\", \"Days in Sales Stage Age Group\", \"Days in Sales Stage\", \"Sales Stage\", \"Industry\", \"Created Month\", \"Date\"}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Removed Other Columns\",{{\"Translated Account\", Text.Trim, type text}}),",
                "    #\"Cleaned Text\" = Table.TransformColumns(#\"Trimmed Text\",{{\"Translated Account\", Text.Clean, type text}}),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Cleaned Text\",{{\"Qualified Pipeline\", Int64.Type}})",
                "in",
                "    #\"Changed Type4\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "WECohort",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "len('WECohort'[Translated Account])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e72cbb4a-2bb3-4322-a82d-d472f48095ff",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Committed Pipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a621f388-8969-4993-b283-6974f5cd1a0e",
            "sourceColumn": "Committed Pipeline",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd mmmm yyyy",
            "lineageTag": "9516d462-1134-4e9d-b282-77ca9ee09af2",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DATEDIFF('WECohort'[Est. Start Date],'WECohort'[Est. Completion Date],DAY)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "4890a29e-c3c8-48e7-bd65-bf7765d4bc3d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Est. Completion Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "7d3f9def-3ab2-4dd7-a1aa-5cc40a7bc274",
            "sourceColumn": "Est. Completion Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a2335a29-0813-43ca-8d8a-b50eae7ca3d2"
                },
                "isDefault": true,
                "relationship": "9f21b99b-9cfd-47ab-81e9-c88da99a1e44"
              }
            ]
          },
          {
            "name": "Est. Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "89c34810-4b34-4738-90e7-35a20a384688",
            "sourceColumn": "Est. Start Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2ba381bf-04fa-46af-a844-f8c961d9e64e"
                },
                "isDefault": true,
                "relationship": "b24e4931-4449-4755-ba8c-b1db683ee1f2"
              }
            ]
          },
          {
            "name": "Industry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "800f9698-c720-4f7d-9332-d5fc84443750",
            "sourceColumn": "Industry",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(WECohort[Date],\"mmmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "fd6870b4-0364-4725-8597-100d9c9f893d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Non-Qualified Pipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "lineageTag": "f595b95b-2359-42f9-8e9c-ae5f78c54031",
            "sourceColumn": "Non-Qualified Pipeline",
            "summarizeBy": "sum"
          },
          {
            "name": "Opportunity Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78e2d3eb-9b11-47c1-885a-66b033a0b55f",
            "sourceColumn": "Opportunity Name",
            "summarizeBy": "none"
          },
          {
            "name": "Opportunity Owner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdd873b4-9e82-4e61-b716-278835eff343",
            "sourceColumn": "Opportunity Owner",
            "summarizeBy": "none"
          },
          {
            "name": "Qualified Pipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "39b52612-546c-4076-ae00-1f75a986ffb8",
            "sourceColumn": "Qualified Pipeline",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales Stage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ea9d4d6-5daf-4b46-960b-c289003dfc24",
            "sourceColumn": "Sales Stage",
            "summarizeBy": "none"
          },
          {
            "name": "SubRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b93b9d9-0c87-4797-9f52-dddebbd6cfef",
            "sourceColumn": "SubRegion",
            "summarizeBy": "none"
          },
          {
            "name": "Subsidiary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e8ea69f-94ce-4c87-b325-8a8ca42cf1e2",
            "sourceColumn": "Subsidiary",
            "summarizeBy": "none"
          },
          {
            "name": "TPID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9403875-e906-466b-8875-05d8891e3e54",
            "sourceColumn": "TPID",
            "summarizeBy": "none"
          },
          {
            "name": "TP_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "15ac2233-112d-4a4e-b193-ffbd9c3483c9",
            "sourceColumn": "TP_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Translated Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3733b5e1-dfb7-4bf8-b7c5-e580781e6d24",
            "sourceColumn": "Translated Account",
            "summarizeBy": "none"
          },
          {
            "name": "Uncommitted Pipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d2cc94ff-e397-45b8-b86e-8f68dc2310b9",
            "sourceColumn": "Uncommitted Pipeline",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "0364926d-1f29-44d5-a60b-de315e7c7756",
        "measures": [
          {
            "name": "Non Qualified (Running WE Cohort FSI) Avg",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "var last =CALCULATE(",
              "                                      [We_non Qualified Pipeline],",
              "                                      FILTER( ALL('WECohort'[Date]),'WECohort'[Date]<=MAX('WECohort'[Date])))",
              "",
              " var FS = CALCULATE(",
              "                                      [We_non Qualified Pipeline],",
              "                                      FILTER( ALL('WECohort'[Date]),'WECohort'[Date]<=MAX('WECohort'[Date])-1))                                     ",
              "",
              "",
              "Return",
              "Divide((last-FS),FS)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "621ce8c0-3e45-4e01-865a-ee0d051de447"
          },
          {
            "name": "Qualified (Running WE Cohort FSI) Avg",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "var last =CALCULATE(",
              "                                      [We_Qualified Pipeline],",
              "                                      FILTER( ALL('WECohort'[Date]),'WECohort'[Date]<=MAX('WECohort'[Date])))",
              "",
              " var FS = CALCULATE(",
              "                                      [We_Qualified Pipeline],",
              "                                      FILTER( ALL('WECohort'[Date]),'WECohort'[Date]<=MAX('WECohort'[Date])-1))                                     ",
              "",
              "",
              "Return",
              "Divide((last-FS),FS)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "794422e5-cedf-43b9-b6d2-dff228c59c2b"
          },
          {
            "name": "Qualified (Running WE Cohort FSI)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(",
              "                                      [We_Qualified Pipeline],",
              "                                      FILTER( ALL('WECohort'[Date]),'WECohort'[Date]<=MAX('WECohort'[Date])))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d4786b65-421c-4baa-9edf-e09028c493c3"
          },
          {
            "name": "WE FSI Color Code",
            "expression": "SWITCH(SELECTEDVALUE('WECohort'[Date]),DATE(2023,04,18),\"#FF8420\",DATE(2023,05,08),\"#E75542\")",
            "lineageTag": "2731fec1-0201-4aa9-8b4f-438f97920ce7"
          },
          {
            "name": "WE  ACR Value running",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "                    CALCULATE(SUM(ACR[Value]),USERELATIONSHIP('WECohort'[Translated Account],ACR[Account]) ,",
              "                    CROSSFILTER('Canada FSI Cohorts'[Translated Account],ACR[Account],None),",
              "                     ALLSELECTED(ACR[Month]) ,",
              "                     FILTER(ALLSELECTED(ACR[Month No]),",
              "                     ACR[Month No]<=MAX(ACR[Month No])))"
            ],
            "lineageTag": "b8b43977-d1d1-49c4-9707-59fcd307d9ae"
          },
          {
            "name": "Pivot WE Non Qualified",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM('pivot_WE Cohort'[Sum of Non-Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "07a14a01-ba30-4154-91b1-91ba00d04f2b"
          },
          {
            "name": "Pivot_WE Cohort Qualified Pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM('pivot_WE Cohort'[Sum of Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ed7d42d1-aa90-41de-88fd-141c5539a565"
          },
          {
            "name": "We_non Qualified Pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM('WECohort'[Non-Qualified Pipeline]))",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ac866256-dd64-43df-bcba-2337acb2ad40"
          },
          {
            "name": "Non Qualified (Running WE Cohort FSI)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(",
              "                                      [We_non Qualified Pipeline],",
              "                                      FILTER( ALL('WECohort'[Date]),'WECohort'[Date]<=MAX('WECohort'[Date])))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "63c11ef8-f7be-47b1-9149-e4d81d96873d"
          },
          {
            "name": "We_Qualified Pipeline",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM('WECohort'[Qualified Pipeline]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "74a41b65-a1b1-4507-91f9-2fc9f95ecf71"
          },
          {
            "name": "New Non Qualified (Running WE Cohort FSI)",
            "expression": [
              "CALCULATE(",
              "                                      [We_non Qualified Pipeline],",
              "                                      FILTER( ALL('WECohort'[Month Name]),'WECohort'[Month Name]<=MAX('WECohort'[Month Name])))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "31870878-3370-4ef0-a5e6-cd19c271c4b2"
          },
          {
            "name": "New_Qualified (Running WE Cohort FSI)",
            "expression": [
              "CALCULATE(",
              "                                      [We_Qualified Pipeline],",
              "                                      FILTER( ALL('WECohort'[Month Name]),'WECohort'[Month Name]<=MAX('WECohort'[Month Name])))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "2ad64551-a2be-488c-b6c0-f90bff83ed29"
          }
        ],
        "partitions": [
          {
            "name": "WECohort-69007178-47cb-4312-b8a7-a4722c8dc0bb",
            "mode": "import",
            "queryGroup": "Fact-Table",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\pradumn.sengar\\Downloads\\datat\\Stage 1 & 2 Pipeline Data\\WE FSI\\May 22nd - WE Cohorts Pipeline .xlsx\"), null, true),",
                "    Export_Sheet = Source{[Item=\"Export\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"MSX\", type text}, {\"Translated Account\", type text}, {\"TPID\", type text}, {\"MACC Account\", type text}, {\"Opportunity Name\", type text}, {\"Qualified Pipeline\", type number}, {\"Non-Qualified Pipeline\", type any}, {\"Committed Pipeline\", type number}, {\"Uncommitted Pipeline\", type number}, {\"Days in Sales Stage Age Group\", type text}, {\"Days in Sales Stage\", Int64.Type}, {\"Opportunity Number\", type text}, {\"Sales Stage\", type text}, {\"Est. Start Date\", type date}, {\"Est. Completion Date\", type date}, {\"MCS Engaged Flag\", type text}, {\"Opportunity Owner\", type text}, {\"Preferred Azure Region\", type text}, {\"Partner Sharing Status\", type text}, {\"SubRegion\", type text}, {\"Subsidiary\", type text}, {\"Field Summary Segment\", type text}, {\"Industry\", type text}, {\"Compete Threat Level\", type text}, {\"Primary Competitor\", type text}, {\"Opportunity Narrative\", type text}, {\"Customer Needs\", type text}, {\"Opportunity Next Steps\", type text}, {\"Opty. Count\", Int64.Type}, {\"Opportunity CreatedBy Group\", type text}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"TPID\", \"TPID - Copy\"),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Duplicated Column\", \"TPID - Copy\", Splitter.SplitTextByDelimiter(\"/\", QuoteStyle.Csv), {\"TPID - Copy.1\", \"TPID - Copy.2\", \"TPID - Copy.3\", \"TPID - Copy.4\", \"TPID - Copy.5\", \"TPID - Copy.6\", \"TPID - Copy.7\", \"TPID - Copy.8\", \"TPID - Copy.9\", \"TPID - Copy.10\", \"TPID - Copy.11\", \"TPID - Copy.12\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"TPID - Copy.1\", type text}, {\"TPID - Copy.2\", type text}, {\"TPID - Copy.3\", type text}, {\"TPID - Copy.4\", type text}, {\"TPID - Copy.5\", type text}, {\"TPID - Copy.6\", Int64.Type}, {\"TPID - Copy.7\", type text}, {\"TPID - Copy.8\", type text}, {\"TPID - Copy.9\", Int64.Type}, {\"TPID - Copy.10\", type text}, {\"TPID - Copy.11\", type text}, {\"TPID - Copy.12\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"TPID - Copy.1\", \"TPID - Copy.2\", \"TPID - Copy.3\", \"TPID - Copy.4\", \"TPID - Copy.5\", \"TPID - Copy.6\", \"TPID - Copy.7\", \"TPID - Copy.8\", \"TPID - Copy.9\", \"TPID - Copy.10\", \"TPID - Copy.11\"}),",
                "    #\"Split Column by Delimiter1\" = Table.SplitColumn(#\"Removed Columns\", \"TPID - Copy.12\", Splitter.SplitTextByDelimiter(\"&\", QuoteStyle.Csv), {\"TPID - Copy.12.1\", \"TPID - Copy.12.2\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Split Column by Delimiter1\",{{\"TPID - Copy.12.1\", Int64.Type}, {\"TPID - Copy.12.2\", type text}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type2\",{\"TPID - Copy.12.2\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns1\",{{\"TPID - Copy.12.1\", \"TP_ID\"}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Renamed Columns\",{{\"Translated Account\", Text.Trim, type text}}),",
                "    #\"Cleaned Text\" = Table.TransformColumns(#\"Trimmed Text\",{{\"Translated Account\", Text.Clean, type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Cleaned Text\", \"Custom\", each Text.Length([Translated Account])),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each true),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Filtered Rows\",{{\"As of Date\", \"Date\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed Columns1\",{\"Translated Account\", \"TPID\", \"Opportunity Name\", \"Qualified Pipeline\", \"Non-Qualified Pipeline\", \"Committed Pipeline\", \"Uncommitted Pipeline\", \"Sales Stage\", \"Est. Start Date\", \"Est. Completion Date\", \"Opportunity Owner\", \"SubRegion\", \"Subsidiary\", \"Industry\", \"Date\", \"TP_ID\"}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Removed Other Columns\",{{\"Date\", type date}, {\"Non-Qualified Pipeline\", type number}})",
                "in",
                "    #\"Changed Type3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "WE_BDM",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "# Stakeholder Map",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c180dc3a-1176-483a-a87a-dd768efdb265",
            "sourceColumn": "# Stakeholder Map",
            "summarizeBy": "sum"
          },
          {
            "name": "# of Contacts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dd85e228-d041-4a54-8b26-6c074daff52a",
            "sourceColumn": "# of Contacts",
            "summarizeBy": "sum"
          },
          {
            "name": "Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "381aabf0-f534-4ef8-9b44-aa83460cd592",
            "sourceColumn": "Account",
            "summarizeBy": "none"
          },
          {
            "name": "Custom",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3d26068-5b89-4774-84d7-3c5a9f63d343",
            "sourceColumn": "Custom",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1ee5e607-139e-44c4-85c6-efe8e0dd3a25",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Date_New",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('WE_BDM'[Date],\"mmmm-dd-yyyy\")",
            "lineageTag": "cc6fcd47-e1ef-4e65-a8ef-5e3bac7b5397",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "IT BDMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "08fb7bbb-9fe1-4f24-97e6-230477f64c22",
            "sourceColumn": "IT BDMS",
            "summarizeBy": "sum"
          },
          {
            "name": "Non IT BDM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "33927cdb-04e3-42dc-b409-762438d8f766",
            "sourceColumn": "Non IT BDM",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f614c66a-3072-4a39-8d59-d74d700892f5",
        "measures": [
          {
            "name": "NonIT BDM_WE",
            "expression": "CALCULATE(SUM('WE_BDM'[Non IT BDM]))",
            "formatString": "0",
            "lineageTag": "061fad2a-2c05-4351-b507-c38dbeb76fb7"
          },
          {
            "name": "IT BDMs WE",
            "expression": "CALCULATE(SUM('WE_BDM'[IT BDMs]))",
            "formatString": "0",
            "lineageTag": "dde1dbd2-3c41-4316-9807-7eee7c41fcfd"
          }
        ],
        "partitions": [
          {
            "name": "WE_BDM-efb541e0-bb0e-486a-baff-d9f7cbc3cf04",
            "mode": "import",
            "queryGroup": "Fact-Table",
            "source": {
              "expression": [
                "let",
                "    Source = #\"WE bdm\",",
                "    #\"Added Custom\" = Table.AddColumn(Source, \"len column1\", each Text.Length([Account Name])),",
                "    #\"Inserted Text Before Delimiter\" = Table.AddColumn(#\"Added Custom\", \"Text Before Delimiter\", each Text.BeforeDelimiter([Account Name], \"\"), type text),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Text Before Delimiter\",{{\"Text Before Delimiter\", \"New Account\"}}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Renamed Columns\", \"Custom\", each Text.Length([New Account])),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom2\",{\"Account Name\",  \"len column1\",  \"Custom\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns\",{{\"New Account\", \"Account\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns1\",\"Crelan\",\"CRELAN\",Replacer.ReplaceText,{\"Account\"}),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Replaced Value\", \"Custom\", each Text.Length([Account])),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom3\",{{\"Date of Data Pull\", \"Date\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"Date\", type date}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"IT BDMS\", each [#\"# of Contacts\"]-[Non IT BDM]),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom1\", each ([Account] <> \"\")),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"IT BDMS\", Int64.Type}, {\"Non IT BDM\", Int64.Type}, {\"# of Contacts\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}